import { DialogPosition, DialogWidth, LogoTheme, SCENE_CHANGE_DELAY } from '../../constants/constants';
import { SceneData } from '../../types/interfaces';

// Character colors
const MAYA_COLOR = '#2D5A27'; // Forest green for Maya
const REYES_COLOR = '#8B4513'; // Saddle brown for Dr. Reyes

export const sceneData: SceneData[] = [
  // ==================== SCENE 1: Title Screen ====================
  {
    name: 'scenesList.scene_1',
    background: {
      alt: 'scenes.common.bg1_description',
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      initialZoom: 1.05,
    },
    logoTheme: {
      landscape: LogoTheme.DARK,
      portrait: LogoTheme.LIGHT,
    },
    audioUrl: '/assets/audio/bgmusic.mp3',
    type: 'one-at-a-time',
    dialogs: [
      {
        heading: 'start.title',
        body: 'start.description',
        headingColor: '#000',
        disableAnimation: true,
        position: {
          left: DialogPosition.START_SCREEN_LEFT,
          top: DialogPosition.START_SCREEN_TOP,
        },
        width: DialogWidth.START_SCREEN,
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: 'scenes.common.char1_description',
          size: 'chat-bubble-square',
          background: '#90EE90',
        },
        controls: [
          {
            type: 'start',
            text: 'start.start_game',
          },
        ],
        background: {
          blur: 4,
          zoom: 1.06,
        },
      },
    ],
  },

  // ==================== SCENE 2: Act 1 - The Problem ====================
  {
    name: 'scenesList.scene_2',
    background: {
      alt: 'Forest trail',
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 3,
      zoom: 1.03,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d1',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d1_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
    ],
  },

  // Scene 3: Meeting Dr. Reyes
  {
    name: 'scenesList.scene_3',
    background: {
      url: '/assets/backgrounds/bg2_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 3,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act1.d2',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d2_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d3',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d3_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
    ],
  },

  // Scene 4: Carbon Credits Explanation
  {
    name: 'scenesList.scene_4',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 3,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act1.d4',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d4_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d5',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d5_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act1.d6',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d6_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
    ],
  },

  // Scene 5: The Challenge (measuring the oak)
  {
    name: 'scenesList.scene_5',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 2,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d7',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d7_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act1.d8',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d8_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d9',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d9_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d10',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d10_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d11',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d11_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
    ],
  },

  // Scene 6: Impossible Methods
  {
    name: 'scenesList.scene_6',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 3,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act1.d12',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d12_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d13',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d13_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act1.d14',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d14_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d15',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d15_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act1.d16',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d16_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act1.d17',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d17_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act1.d18',
        audioUrl: '/assets/audio/da-vinci-trees_act1_d18_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
    ],
  },

  // ==================== SCENE 7: Act 2 - Da Vinci's Rule ====================
  {
    name: 'scenesList.scene_7',
    background: {
      url: '/assets/backgrounds/bg2_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 3,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d19',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d19_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d20',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d20_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d21',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d21_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d22',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d22_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d23',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d23_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d24',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d24_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
    ],
  },

  // Scene 8: Da Vinci Introduction
  {
    name: 'scenesList.scene_8',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 4,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d25',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d25_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d26',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d26_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d27',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d27_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d28',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d28_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
        glossary: [
          {
            word: 'scenes.glossary.cross_section.word',
            definitionAsHtml: 'scenes.glossary.cross_section.definition',
          },
        ],
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d29',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d29_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d30',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d30_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
    ],
  },

  // Scene 8b: Cross-Section Rule Interactive
  {
    name: 'scenesList.scene_8b',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 6,
      zoom: 1.0,
    },
    type: 'split-screen-chat',
    leftConfig: {
      blur: 0,
      background: 'rgba(255, 255, 255, 0.4)',
    },
    dialogs: [
      {
        isPrimaryHeading: true,
        side: 'left',
        skipNavigation: true,
        heading: 'scenes.cross_section.heading',
        headingColor: '#000',
        interactions: [
          {
            name: 'cross-section-rule',
            config: 'cross-section-rule',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.cross_section.d1',
        audioUrl: '/assets/audio/da-vinci-trees_cross_section_d1_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.cross_section.d2',
        audioUrl: '/assets/audio/da-vinci-trees_cross_section_d2_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.cross_section.d3',
        audioUrl: '/assets/audio/da-vinci-trees_cross_section_d3_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.cross_section.d4',
        audioUrl: '/assets/audio/da-vinci-trees_cross_section_d4_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.cross_section.d5',
        audioUrl: '/assets/audio/da-vinci-trees_cross_section_d5_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.cross_section.d6',
        audioUrl: '/assets/audio/da-vinci-trees_cross_section_d6_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.cross_section.d7',
        audioUrl: '/assets/audio/da-vinci-trees_cross_section_d7_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.cross_section.d8',
        audioUrl: '/assets/audio/da-vinci-trees_cross_section_d8_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
    ],
  },

  // Scene 9: Pipe Model Explanation
  {
    name: 'scenesList.scene_9',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 4,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d31',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d31_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d32',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d32_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d33',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d33_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d34',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d34_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d35',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d35_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
    ],
  },

  // ==================== SCENE 10: Da Vinci Tree Interactive ====================
  {
    name: 'scenesList.scene_10',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
    },
    type: 'split-screen-chat',
    leftConfig: {
      blur: 0,
      background: 'rgba(255, 255, 255, 0.4)',
    },
    dialogs: [
      {
        isPrimaryHeading: true,
        side: 'left',
        skipNavigation: true,
        heading: 'scenes.act2.interactive_title',
        headingColor: '#000',
        interactions: [
          {
            name: 'da-vinci-tree',
            config: 'da-vinci-tree',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d37',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d37_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d38',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d38_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d41',
        audioUrl: '/assets/audio/da-vinci-trees_act2_d41_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d42',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d43',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d44',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act2.d45_math',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act2.d45_interactive',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
    ],
  },

  // ==================== SCENE 11: Question 1 - Da Vinci Rule ====================
  {
    name: 'scenesList.scene_11',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.q1.heading',
        headingColor: '#333',
        bodyAsHtml: 'scenes.q1.stem',
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'back',
          },
          {
            type: 'submit',
          },
        ],
        interactions: [
          {
            name: 'interactive-radio',
            config: 'q1-da-vinci-rule',
          },
        ],
      },
    ],
  },

  // ==================== SCENE 12: Act 3 - Calculating Volume ====================
  {
    name: 'scenesList.scene_12',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 3,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act3.d43',
        audioUrl: '/assets/audio/da-vinci-trees_act3_d43_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act3.d44',
        audioUrl: '/assets/audio/da-vinci-trees_act3_d44_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act3.d45',
        audioUrl: '/assets/audio/da-vinci-trees_act3_d45_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
        glossary: [
          {
            word: 'scenes.glossary.dbh.word',
            definitionAsHtml: 'scenes.glossary.dbh.definition',
          },
        ],
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act3.d46',
        audioUrl: '/assets/audio/da-vinci-trees_act3_d46_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act3.d47',
        audioUrl: '/assets/audio/da-vinci-trees_act3_d47_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act3.d48',
        audioUrl: '/assets/audio/da-vinci-trees_act3_d48_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
    ],
  },

  // ==================== SCENE 13: Question 2 - Cylinder Volume ====================
  {
    name: 'scenesList.scene_13',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.q2.heading',
        headingColor: '#333',
        bodyAsHtml: 'scenes.q2.stem',
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'back',
          },
          {
            type: 'submit',
          },
        ],
        interactions: [
          {
            name: 'interactive-radio',
            config: 'q2-cylinder-volume',
          },
        ],
      },
    ],
  },

  // Scene 14: Carbon Calculation
  {
    name: 'scenesList.scene_14',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 3,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act3.d50',
        audioUrl: '/assets/audio/da-vinci-trees_act3_d50_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act3.d51',
        audioUrl: '/assets/audio/da-vinci-trees_act3_d51_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act3.d52',
        audioUrl: '/assets/audio/da-vinci-trees_act3_d52_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
    ],
  },

  // ==================== SCENE 15: Question 3 - Carbon Storage ====================
  {
    name: 'scenesList.scene_15',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.q3.heading',
        headingColor: '#333',
        bodyAsHtml: 'scenes.q3.stem',
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'back',
          },
          {
            type: 'submit',
          },
        ],
        interactions: [
          {
            name: 'interactive-radio',
            config: 'q3-carbon-storage',
          },
        ],
      },
    ],
  },

  // ==================== SCENE 16: Act 4 - Conifers ====================
  {
    name: 'scenesList.scene_16',
    background: {
      url: '/assets/backgrounds/bg4_conifer.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 2,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act4.d54',
        audioUrl: '/assets/audio/da-vinci-trees_act4_d54_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act4.d55',
        audioUrl: '/assets/audio/da-vinci-trees_act4_d55_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
        glossary: [
          {
            word: 'scenes.glossary.conifer.word',
            definitionAsHtml: 'scenes.glossary.conifer.definition',
          },
        ],
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act4.d56',
        audioUrl: '/assets/audio/da-vinci-trees_act4_d56_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act4.d57',
        audioUrl: '/assets/audio/da-vinci-trees_act4_d57_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act4.d58',
        audioUrl: '/assets/audio/da-vinci-trees_act4_d58_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act4.d59',
        audioUrl: '/assets/audio/da-vinci-trees_act4_d59_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act4.d60',
        audioUrl: '/assets/audio/da-vinci-trees_act4_d60_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
    ],
  },

  // ==================== SCENE 17: Conifer Interactive ====================
  {
    name: 'scenesList.scene_17',
    background: {
      url: '/assets/backgrounds/bg4_conifer.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
    },
    type: 'split-screen-chat',
    leftConfig: {
      blur: 0,
      background: 'rgba(255, 255, 255, 0.4)',
    },
    dialogs: [
      {
        isPrimaryHeading: true,
        side: 'left',
        skipNavigation: true,
        heading: 'scenes.act4.interactive_title',
        headingColor: '#000',
        interactions: [
          {
            name: 'conifer-tree',
            config: 'conifer-tree',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.conifer_tree.d1',
        audioUrl: '/assets/audio/da-vinci-trees_conifer_tree_d1_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.conifer_tree.d2',
        audioUrl: '/assets/audio/da-vinci-trees_conifer_tree_d2_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.conifer_tree.d3',
        audioUrl: '/assets/audio/da-vinci-trees_conifer_tree_d3_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.conifer_tree.d4',
        audioUrl: '/assets/audio/da-vinci-trees_conifer_tree_d4_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.conifer_tree.d5',
        audioUrl: '/assets/audio/da-vinci-trees_conifer_tree_d5_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.conifer_tree.d6',
        audioUrl: '/assets/audio/da-vinci-trees_conifer_tree_d6_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.conifer_tree.d7',
        audioUrl: '/assets/audio/da-vinci-trees_conifer_tree_d7_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.conifer_tree.d8',
        audioUrl: '/assets/audio/da-vinci-trees_conifer_tree_d8_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
    ],
  },

  // ==================== SCENE 18: Question 4 - Cone Volume ====================
  {
    name: 'scenesList.scene_18',
    background: {
      url: '/assets/backgrounds/bg4_conifer.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.q4.heading',
        headingColor: '#333',
        bodyAsHtml: 'scenes.q4.stem',
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'back',
          },
          {
            type: 'submit',
          },
        ],
        interactions: [
          {
            name: 'interactive-radio',
            config: 'q4-cone-volume',
          },
        ],
      },
    ],
  },

  // ==================== SCENE 19: Question 5 - Cylinder Overestimate ====================
  {
    name: 'scenesList.scene_19',
    background: {
      url: '/assets/backgrounds/bg4_conifer.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.q5.heading',
        headingColor: '#333',
        bodyAsHtml: 'scenes.q5.stem',
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'back',
          },
          {
            type: 'submit',
          },
        ],
        interactions: [
          {
            name: 'interactive-radio',
            config: 'q5-cylinder-overestimate',
          },
        ],
      },
    ],
  },

  // ==================== SCENE 20: Act 5 - Form Factor ====================
  {
    name: 'scenesList.scene_20',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 3,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act5.d64',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d64_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act5.d65',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d65_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act5.d66',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act5.d67',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d67_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act5.d68',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d68_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act5.d69',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d69_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act5.d70',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d70_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act5.d71',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d71_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
        glossary: [
          {
            word: 'scenes.glossary.form_factor.word',
            definitionAsHtml: 'scenes.glossary.form_factor.definition',
          },
        ],
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act5.d72',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d72_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
    ],
  },

  // Scene 20b: Form Factor Interactive
  {
    name: 'scenesList.scene_20b',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 6,
      zoom: 1.0,
    },
    type: 'split-screen-chat',
    leftConfig: {
      blur: 0,
      background: 'rgba(255, 255, 255, 0.4)',
    },
    dialogs: [
      {
        isPrimaryHeading: true,
        side: 'left',
        skipNavigation: true,
        heading: 'scenes.form_factor.heading',
        headingColor: '#000',
        interactions: [
          {
            name: 'form-factor',
            config: 'form-factor',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.form_factor.d1',
        audioUrl: '/assets/audio/da-vinci-trees_form_factor_d1_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.form_factor.d2',
        audioUrl: '/assets/audio/da-vinci-trees_form_factor_d2_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.form_factor.d3',
        audioUrl: '/assets/audio/da-vinci-trees_form_factor_d3_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.form_factor.d4',
        audioUrl: '/assets/audio/da-vinci-trees_form_factor_d4_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.form_factor.d5',
        audioUrl: '/assets/audio/da-vinci-trees_form_factor_d5_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.form_factor.d6',
        audioUrl: '/assets/audio/da-vinci-trees_form_factor_d6_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.form_factor.d7',
        audioUrl: '/assets/audio/da-vinci-trees_form_factor_d7_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.form_factor.d8',
        audioUrl: '/assets/audio/da-vinci-trees_form_factor_d8_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
    ],
  },

  // ==================== SCENE 21: Volume Comparison Interactive ====================
  {
    name: 'scenesList.scene_21',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
    },
    type: 'split-screen-chat',
    leftConfig: {
      blur: 0,
      background: 'rgba(255, 255, 255, 0.4)',
    },
    dialogs: [
      {
        isPrimaryHeading: true,
        side: 'left',
        skipNavigation: true,
        heading: 'scenes.act5.interactive_title',
        headingColor: '#000',
        interactions: [
          {
            name: 'volume-comparison',
            config: 'volume-comparison',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.volume_comparison.d1',
        audioUrl: '/assets/audio/da-vinci-trees_volume_comparison_d1_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.volume_comparison.d2',
        audioUrl: '/assets/audio/da-vinci-trees_volume_comparison_d2_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.volume_comparison.d3',
        audioUrl: '/assets/audio/da-vinci-trees_volume_comparison_d3_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.volume_comparison.d4',
        audioUrl: '/assets/audio/da-vinci-trees_volume_comparison_d4_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.volume_comparison.d5',
        audioUrl: '/assets/audio/da-vinci-trees_volume_comparison_d5_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.volume_comparison.d6',
        audioUrl: '/assets/audio/da-vinci-trees_volume_comparison_d6_C1_en.mp3',
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'medium',
          position: 'left',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.volume_comparison.d7',
        audioUrl: '/assets/audio/da-vinci-trees_volume_comparison_d7_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
      {
        side: 'right',
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.volume_comparison.d8',
        audioUrl: '/assets/audio/da-vinci-trees_volume_comparison_d8_C2_en.mp3',
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'medium',
          position: 'right',
        },
      },
    ],
  },

  // ==================== SCENE 22: Question 6 - Form Factor ====================
  {
    name: 'scenesList.scene_22',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.q6.heading',
        headingColor: '#333',
        bodyAsHtml: 'scenes.q6.stem',
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'back',
          },
          {
            type: 'submit',
          },
        ],
        interactions: [
          {
            name: 'interactive-radio',
            config: 'q6-form-factor',
          },
        ],
      },
    ],
  },

  // Scene 23: Refined Formula
  {
    name: 'scenesList.scene_23',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 3,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act5.d74',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d74_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act5.d76',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d76_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act5.d77',
        audioUrl: '/assets/audio/da-vinci-trees_act5_d77_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
    ],
  },

  // ==================== SCENE 24: Question 7 - Recalculate ====================
  {
    name: 'scenesList.scene_24',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.q7.heading',
        headingColor: '#333',
        bodyAsHtml: 'scenes.q7.stem',
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'back',
          },
          {
            type: 'submit',
          },
        ],
        interactions: [
          {
            name: 'interactive-radio',
            config: 'q7-recalculate',
          },
        ],
      },
    ],
  },

  // ==================== SCENE 25: Question 7b - Model Choice ====================
  {
    name: 'scenesList.scene_25',
    background: {
      url: '/assets/backgrounds/bg3_new.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.q7b.heading',
        headingColor: '#333',
        bodyAsHtml: 'scenes.q7b.stem',
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'back',
          },
          {
            type: 'submit',
          },
        ],
        interactions: [
          {
            name: 'interactive-radio',
            config: 'q7b-model-choice',
          },
        ],
      },
    ],
  },

  // ==================== SCENE 26: Act 6 - Scaling Up ====================
  {
    name: 'scenesList.scene_26',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 2,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act6.d78',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d78_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act6.d79',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d79_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
        glossary: [
          {
            word: 'scenes.glossary.sampling.word',
            definitionAsHtml: 'scenes.glossary.sampling.definition',
          },
        ],
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act6.d80',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d80_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act6.d81',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d81_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act6.d82_new',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d82_new_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act6.d83_new',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d83_new_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act6.d84_new',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d84_new_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act6.d85_new',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d85_new_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act6.d86_new',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d86_new_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act6.d87_new',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d87_new_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act6.d82',
        audioUrl: '/assets/audio/da-vinci-trees_act6_d82_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
    ],
  },

  // ==================== SCENE 27: Question 8 - Forest Carbon ====================
  {
    name: 'scenesList.scene_27',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.q8.heading',
        headingColor: '#333',
        bodyAsHtml: 'scenes.q8.stem',
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'back',
          },
          {
            type: 'submit',
          },
        ],
        interactions: [
          {
            name: 'interactive-radio',
            config: 'q8-forest-carbon',
          },
        ],
      },
    ],
  },

  // ==================== SCENE 28: Act 7 - Conclusion ====================
  {
    name: 'scenesList.scene_28',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 2,
      zoom: 1.02,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act7.d83',
        audioUrl: '/assets/audio/da-vinci-trees_act7_d83_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act7.d84',
        audioUrl: '/assets/audio/da-vinci-trees_act7_d84_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act7.d86',
        audioUrl: '/assets/audio/da-vinci-trees_act7_d86_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act7.d87',
        audioUrl: '/assets/audio/da-vinci-trees_act7_d87_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act7.d88',
        audioUrl: '/assets/audio/da-vinci-trees_act7_d88_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char2',
        headingColor: REYES_COLOR,
        bodyAsHtml: 'scenes.act7.d89',
        audioUrl: '/assets/audio/da-vinci-trees_act7_d89_C2_en.mp3',
        position: { top: '50%', left: '38%' },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: 'Dr. Reyes',
          size: 'large',
          position: 'right',
        },
        width: '56vw',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.char1',
        headingColor: MAYA_COLOR,
        bodyAsHtml: 'scenes.act7.d90',
        audioUrl: '/assets/audio/da-vinci-trees_act7_d90_C1_en.mp3',
        position: { top: '50%', left: '63%' },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: 'Maya',
          size: 'large',
          position: 'left',
        },
        width: '56vw',
      },
    ],
  },

  // ==================== SCENE 29: End Screen ====================
  {
    name: 'scenesList.scene_29',
    background: {
      url: '/assets/backgrounds/bg1_oak.png',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 5,
      zoom: 1.05,
    },
    type: 'end-screen',
    dialogs: [
      {
        heading: 'end.title',
        bodyAsHtml: 'end.summary',
        headingColor: '#000',
        disableAnimation: true,
        position: { top: '50%', left: '50%' },
        width: '80vw',
        controls: [
          {
            type: 'start',
            text: 'dialog.button.start_again',
          },
        ],
      },
    ],
  },
];
