const interaction = {
  translations: {
    hideGuide: 'scenes.S8.S8_D0_F58_C9.translations.hideGuide',
    showGuide: 'scenes.S8.S8_D0_F58_C9.translations.showGuide',
    dataLegend: 'scenes.S8.S8_D0_F58_C9.translations.dataLegend',
    scaleLegend: 'scenes.S8.S8_D0_F58_C9.translations.scaleLegend',
    addPoint: 'scenes.S8.S8_D0_F58_C9.translations.addPoint',
    reset: 'scenes.S8.S8_D0_F58_C9.translations.reset',
    selectedPoints: 'scenes.S8.S8_D0_F58_C9.translations.selectedPoints',
    deletePoint: 'scenes.S8.S8_D0_F58_C9.translations.deletePoint',
    status: 'scenes.S8.S8_D0_F58_C9.translations.status',
    statusDescription1: 'scenes.S8.S8_D0_F58_C9.translations.statusDescription1',
    statusDescription2: 'scenes.S8.S8_D0_F58_C9.translations.statusDescription2',
    measurementLabel: 'scenes.S8.S8_D0_F58_C9.translations.measurementLabel',
    perimeter: 'scenes.S8.S8_D0_F58_C9.translations.perimeter',
    area: 'scenes.S8.S8_D0_F58_C9.translations.area',
    ratio: 'scenes.S8.S8_D0_F58_C9.translations.ratio',
    rightAngles: 'scenes.S8.S8_D0_F58_C9.translations.rightAngles',
    yes: 'scenes.S8.S8_D0_F58_C9.translations.yes',
    no: 'scenes.S8.S8_D0_F58_C9.translations.no',
    insights: 'scenes.S8.S8_D0_F58_C9.translations.insights',
    insightsDescription1: 'scenes.S8.S8_D0_F58_C9.translations.insightsDescription1',
    insightsDescription2: 'scenes.S8.S8_D0_F58_C9.translations.insightsDescription2',
    objetiveLabel: 'scenes.S8.S8_D0_F58_C9.translations.objetiveLabel',
    objetiveDescription: 'scenes.S8.S8_D0_F58_C9.translations.objetiveDescription',
    successLabel: 'scenes.S8.S8_D0_F58_C9.translations.successLabel',
    successDescription: 'scenes.S8.S8_D0_F58_C9.translations.successDescription',
    nextStep: 'scenes.S8.S8_D0_F58_C9.translations.nextStep',
    nextStepDescription: 'scenes.S8.S8_D0_F58_C9.translations.nextStepDescription',
    canvasDescription: 'scenes.S8.S8_D0_F58_C9.translations.canvasDescription',
  },
};

export default interaction;
