const interaction = {
  ariaLabel: 'scenes.S9.S9_D0_F54_C9.ariaLabel',
  translations: {
    title: 'scenes.S9.S9_D0_F54_C9.translations.title',
    treeSpacing: 'scenes.S9.S9_D0_F54_C9.translations.treeSpacing',
    harvestCycle: 'scenes.S9.S9_D0_F54_C9.translations.harvestCycle',
    timberQuality: 'scenes.S9.S9_D0_F54_C9.translations.timberQuality',
    carbonStorage: 'scenes.S9.S9_D0_F54_C9.translations.carbonStorage',
    sustainability: 'scenes.S9.S9_D0_F54_C9.translations.sustainability',
    timberPriority: 'scenes.S9.S9_D0_F54_C9.translations.timberPriority',
    carbonPriority: 'scenes.S9.S9_D0_F54_C9.translations.carbonPriority',
    balancedApproach: 'scenes.S9.S9_D0_F54_C9.translations.balancedApproach',
    years: 'scenes.S9.S9_D0_F54_C9.translations.years',
    densePlanting: 'scenes.S9.S9_D0_F54_C9.translations.densePlanting',
    wideSpacing: 'scenes.S9.S9_D0_F54_C9.translations.wideSpacing',
    balancedSpacing: 'scenes.S9.S9_D0_F54_C9.translations.balancedSpacing',
    trees: 'scenes.S9.S9_D0_F54_C9.translations.trees',
    noTrees: 'scenes.S9.S9_D0_F54_C9.translations.noTrees',
    step: 'scenes.S9.S9_D0_F54_C9.translations.step',
    of: 'scenes.S9.S9_D0_F54_C9.translations.of',
    previous: 'scenes.S9.S9_D0_F54_C9.translations.previous',
    next: 'scenes.S9.S9_D0_F54_C9.translations.next',
    area: 'scenes.S9.S9_D0_F54_C9.translations.area',
    perTree: 'scenes.S9.S9_D0_F54_C9.translations.perTree',
    treesPerAcre: 'scenes.S9.S9_D0_F54_C9.translations.treesPerAcre',
    foot: 'scenes.S9.S9_D0_F54_C9.translations.foot',
    squareFoot: 'scenes.S9.S9_D0_F54_C9.translations.squareFoot',
    illustrationAriaLabel: 'scenes.S9.S9_D0_F54_C9.translations.illustrationAriaLabel',
  },
  scenarios: {
    timber: {
      name: 'scenes.S9.S9_D0_F54_C9.scenarios.timber.name',
      description: 'scenes.S9.S9_D0_F54_C9.scenarios.timber.description',
      step: 1,
      spacing: 12,
      harvestCycle: 40,
      gridSize: 16,
    },
    carbon: {
      name: 'scenes.S9.S9_D0_F54_C9.scenarios.carbon.name',
      description: 'scenes.S9.S9_D0_F54_C9.scenarios.carbon.description',
      step: 2,
      spacing: 20,
      harvestCycle: 80,
      gridSize: 12,
    },
    balanced: {
      name: 'scenes.S9.S9_D0_F54_C9.scenarios.balanced.name',
      description: 'scenes.S9.S9_D0_F54_C9.scenarios.balanced.description',
      step: 3,
      spacing: 16,
      harvestCycle: 50,
      gridSize: 14,
    },
  },
};

export default interaction;
