import { TimberQualityOptimizerInteraction } from '../interactives/interface';

const interaction: TimberQualityOptimizerInteraction = {
  translations: {
    timberQualityOptimizer: 'scenes.S7.S7_D0_F36_C9.labels.timberQualityOptimizer',
    maximizeValue: 'scenes.S7.S7_D0_F36_C9.labels.maximizeValue',
    poorQualityTimber: 'scenes.S7.S7_D0_F36_C9.labels.poorQualityTimber',
    betterHeightRatio: 'scenes.S7.S7_D0_F36_C9.labels.betterHeightRatio',
    strategicThinning: 'scenes.S7.S7_D0_F36_C9.labels.strategicThinning',
    optimalSpacing: 'scenes.S7.S7_D0_F36_C9.labels.optimalSpacing',
    timberQuality: 'scenes.S7.S7_D0_F36_C9.labels.timberQuality',
    timberValue: 'scenes.S7.S7_D0_F36_C9.labels.timberValue',
    carbonStorage: 'scenes.S7.S7_D0_F36_C9.labels.carbonStorage',
    heightRatio: 'scenes.S7.S7_D0_F36_C9.labels.heightRatio',
    thinning: 'scenes.S7.S7_D0_F36_C9.labels.thinning',
    spacing: 'scenes.S7.S7_D0_F36_C9.labels.spacing',
    lowGradeDescription: 'scenes.S7.S7_D0_F36_C9.labels.lowGradeDescription',
    mediumGradeDescription: 'scenes.S7.S7_D0_F36_C9.labels.mediumGradeDescription',
    highGradeDescription: 'scenes.S7.S7_D0_F36_C9.labels.highGradeDescription',
    premiumGradeDescription: 'scenes.S7.S7_D0_F36_C9.labels.premiumGradeDescription',
    carbonPremiumDescription: 'scenes.S7.S7_D0_F36_C9.labels.carbonPremiumDescription',
    maximumPotential: 'scenes.S7.S7_D0_F36_C9.labels.maximumPotential',
    branchThinningShort: 'scenes.S7.S7_D0_F36_C9.labels.branchThinningShort',
    optimalHeightRatioFull: 'scenes.S7.S7_D0_F36_C9.labels.optimalHeightRatioFull',
    branchThinningFull: 'scenes.S7.S7_D0_F36_C9.labels.branchThinningFull',
    spacingShort: 'scenes.S7.S7_D0_F36_C9.labels.spacingShort',
    spacingFull: 'scenes.S7.S7_D0_F36_C9.labels.spacingFull',
    currentStage: 'scenes.S7.S7_D0_F36_C9.labels.currentStage',
    heightToDiameterRatio: 'scenes.S7.S7_D0_F36_C9.labels.heightToDiameterRatio',
    branchThinningLabel: 'scenes.S7.S7_D0_F36_C9.labels.branchThinningLabel',
    treeSpacingLabel: 'scenes.S7.S7_D0_F36_C9.labels.treeSpacingLabel',
    perCubicFoot: 'scenes.S7.S7_D0_F36_C9.labels.perCubicFoot',
    tonsPerAcre: 'scenes.S7.S7_D0_F36_C9.labels.tonsPerAcre',
    optimized: 'scenes.S7.S7_D0_F36_C9.labels.optimized',
    poor: 'scenes.S7.S7_D0_F36_C9.labels.poor',
    applied: 'scenes.S7.S7_D0_F36_C9.labels.applied',
    notApplied: 'scenes.S7.S7_D0_F36_C9.labels.notApplied',
    optimal: 'scenes.S7.S7_D0_F36_C9.labels.optimal',
    suboptimal: 'scenes.S7.S7_D0_F36_C9.labels.suboptimal',
    of: 'scenes.S7.S7_D0_F36_C9.labels.of',
    hdRatio: 'scenes.S7.S7_D0_F36_C9.labels.hdRatio',
    timberValueProgress: 'scenes.S7.S7_D0_F36_C9.labels.timberValueProgress',
    carbonStorageLabel: 'scenes.S7.S7_D0_F36_C9.labels.carbonStorageLabel',
    // 3D viewer labels
    hdRatioLabel: 'scenes.S7.S7_D0_F36_C9.labels.hdRatioLabel',
    spacingLabel: 'scenes.S7.S7_D0_F36_C9.labels.spacingLabel',
    interactive3DView: 'scenes.S7.S7_D0_F36_C9.labels.interactive3DView',
  },
  ariaLabels: {
    timberVisualization: 'scenes.S7.S7_D0_F36_C9.ariaLabels.timberVisualization',
    progressIndicator: 'scenes.S7.S7_D0_F36_C9.ariaLabels.progressIndicator',
    qualityMetrics: 'scenes.S7.S7_D0_F36_C9.ariaLabels.qualityMetrics',
    navigationControls: 'scenes.S7.S7_D0_F36_C9.ariaLabels.navigationControls',
    zoomIn: 'scenes.S7.S7_D0_F36_C9.ariaLabels.zoomIn',
    zoomOut: 'scenes.S7.S7_D0_F36_C9.ariaLabels.zoomOut',
  },
};

export default interaction;
