import { TreeVolumeExplorerInteraction } from '../interactives/interface';

const interaction: TreeVolumeExplorerInteraction = {
  translations: {
    // Step 1: Trunk Geometry
    title: 'scenes.S5.S5_D0_FX_C9.labels.treeVolumeExplorer',
    treeHeight: 'scenes.S5.S5_D0_FX_C9.labels.treeHeight',
    trunkDiameter: 'scenes.S5.S5_D0_FX_C9.labels.trunkDiameter',
    cylindrical: 'scenes.S5.S5_D0_FX_C9.labels.cylindrical',
    conical: 'scenes.S5.S5_D0_FX_C9.labels.conical',
    volumeFormula: 'scenes.S5.S5_D0_FX_C9.labels.volumeFormula',
    cylindricalVolume: 'scenes.S5.S5_D0_FX_C9.labels.cylindricalVolume',
    conicalVolume: 'scenes.S5.S5_D0_FX_C9.labels.conicalVolume',
    leonardoRule: 'scenes.S5.S5_D0_FX_C9.labels.leonardoRule',
    trunkArea: 'scenes.S5.S5_D0_FX_C9.labels.trunkArea',
    branchAreas: 'scenes.S5.S5_D0_FX_C9.labels.branchAreas',
    crossSectionHeight: 'scenes.S5.S5_D0_FX_C9.labels.crossSectionHeight',
    branchAreasSum: 'scenes.S5.S5_D0_FX_C9.labels.branchAreasSum',
    trunkAreaLabel: 'scenes.S5.S5_D0_FX_C9.labels.trunkAreaLabel',
    sum: 'scenes.S5.S5_D0_FX_C9.labels.sum',
    squareFeet: 'scenes.S5.S5_D0_FX_C9.labels.squareFeet',
    cubeFeet: 'scenes.S5.S5_D0_FX_C9.labels.cubeFeet',
    square: 'scenes.S5.S5_D0_FX_C9.labels.square',
    treeType: 'scenes.S5.S5_D0_FX_C9.labels.treeType',
    // Step 2: Branching Explorer
    branchingExplorer: 'scenes.S5.S5_D0_FX_C9.labels.branchingExplorer',
    oakBranching: 'scenes.S5.S5_D0_FX_C9.labels.oakBranching',
    pineBranching: 'scenes.S5.S5_D0_FX_C9.labels.pineBranching',
    branchAngle: 'scenes.S5.S5_D0_FX_C9.labels.branchAngle',
    branchDepth: 'scenes.S5.S5_D0_FX_C9.labels.branchDepth',
    lengthRatio: 'scenes.S5.S5_D0_FX_C9.labels.lengthRatio',
    leonardoExponent: 'scenes.S5.S5_D0_FX_C9.labels.leonardoExponent',
    whorlInterval: 'scenes.S5.S5_D0_FX_C9.labels.whorlInterval',
    branchesPerWhorl: 'scenes.S5.S5_D0_FX_C9.labels.branchesPerWhorl',
    maxBranchLength: 'scenes.S5.S5_D0_FX_C9.labels.maxBranchLength',
    initialAngle: 'scenes.S5.S5_D0_FX_C9.labels.initialAngle',
    droopFactor: 'scenes.S5.S5_D0_FX_C9.labels.droopFactor',
    daVinciRuleCheck: 'scenes.S5.S5_D0_FX_C9.labels.daVinciRuleCheck',
    trunkAreaBranching: 'scenes.S5.S5_D0_FX_C9.labels.trunkAreaBranching',
    branchesAreaSumBranching: 'scenes.S5.S5_D0_FX_C9.labels.branchesAreaSumBranching',
    areaDifference: 'scenes.S5.S5_D0_FX_C9.labels.areaDifference',
    degrees: 'scenes.S5.S5_D0_FX_C9.labels.degrees',
    meters: 'scenes.S5.S5_D0_FX_C9.labels.meters',
  },
  ariaLabels: {
    // Step 1
    treeHeightSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.treeHeightSlider',
    trunkDiameterSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.trunkDiameterSlider',
    cylindricalModelToggle: 'scenes.S5.S5_D0_FX_C9.ariaLabels.cylindricalModelToggle',
    conicalModelToggle: 'scenes.S5.S5_D0_FX_C9.ariaLabels.conicalModelToggle',
    treeVisualization: 'scenes.S5.S5_D0_FX_C9.ariaLabels.treeVisualization',
    // Step 2
    oakBranchingTab: 'scenes.S5.S5_D0_FX_C9.ariaLabels.oakBranchingTab',
    pineBranchingTab: 'scenes.S5.S5_D0_FX_C9.ariaLabels.pineBranchingTab',
    branchAngleSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.branchAngleSlider',
    branchDepthSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.branchDepthSlider',
    lengthRatioSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.lengthRatioSlider',
    leonardoExponentSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.leonardoExponentSlider',
    whorlIntervalSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.whorlIntervalSlider',
    branchesPerWhorlSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.branchesPerWhorlSlider',
    maxBranchLengthSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.maxBranchLengthSlider',
    initialAngleSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.initialAngleSlider',
    droopFactorSlider: 'scenes.S5.S5_D0_FX_C9.ariaLabels.droopFactorSlider',
    oakBranchingVisualization: 'scenes.S5.S5_D0_FX_C9.ariaLabels.oakBranchingVisualization',
    pineBranchingVisualization: 'scenes.S5.S5_D0_FX_C9.ariaLabels.pineBranchingVisualization',
  },
  colors: {
    cylindrical: '#2196F3',
    conical: '#4CAF50',
    trunk: '#5D4037',
    highlight: '#FF9800',
  },
};

export default interaction;
