const interactive0Config = {
  translationKeys: {
    // Ledger entry amounts and descriptions
    twenty_five_dirhams: 'scenes.S9.S9_D0_F23_C9.twenty_five_dirhams',
    fifty_dirhams: 'scenes.S9.S9_D0_F23_C9.fifty_dirhams',
    twenty_dirhams: 'scenes.S9.S9_D0_F23_C9.twenty_dirhams',
    eighteen_dirhams: 'scenes.S9.S9_D0_F23_C9.eighteen_dirhams',
    forty_two_dirhams: 'scenes.S9.S9_D0_F23_C9.forty_two_dirhams',
    eight_dirhams: 'scenes.S9.S9_D0_F23_C9.eight_dirhams',
    twelve_dirhams: 'scenes.S9.S9_D0_F23_C9.twelve_dirhams',
    twenty_eight_dirhams: 'scenes.S9.S9_D0_F23_C9.twenty_eight_dirhams',
    three_pounds_dates_sold: 'scenes.S9.S9_D0_F23_C9.three_pounds_dates_sold',
    seven_pounds_dates_sold: 'scenes.S9.S9_D0_F23_C9.seven_pounds_dates_sold',
    five_pounds_dates_sold: 'scenes.S9.S9_D0_F23_C9.five_pounds_dates_sold',
    shop_rent: 'scenes.S9.S9_D0_F23_C9.shop_rent',
    helper_weekly_wage: 'scenes.S9.S9_D0_F23_C9.helper_weekly_wage',
    date_supply_purchased: 'scenes.S9.S9_D0_F23_C9.date_supply_purchased',
    storage_baskets: 'scenes.S9.S9_D0_F23_C9.storage_baskets',
    market_stall_fee: 'scenes.S9.S9_D0_F23_C9.market_stall_fee',

    // UI interactions and announcements
    started_dragging: 'scenes.S9.S9_D0_F23_C9.started_dragging',
    dropped_into: 'scenes.S9.S9_D0_F23_C9.dropped_into',
    drag_cancelled: 'scenes.S9.S9_D0_F23_C9.drag_cancelled',
    moved_to: 'scenes.S9.S9_D0_F23_C9.moved_to',
    entry_deselected: 'scenes.S9.S9_D0_F23_C9.entry_deselected',
    category_buttons_hidden: 'scenes.S9.S9_D0_F23_C9.category_buttons_hidden',
    selected: 'scenes.S9.S9_D0_F23_C9.selected',
    category_buttons_visible_below: 'scenes.S9.S9_D0_F23_C9.category_buttons_visible_below',

    // Feedback messages
    you_still_have: 'scenes.S9.S9_D0_F23_C9.you_still_have',
    uncategorized_entries: 'scenes.S9.S9_D0_F23_C9.uncategorized_entries',
    please_categorize_all: 'scenes.S9.S9_D0_F23_C9.please_categorize_all',
    excellent: 'scenes.S9.S9_D0_F23_C9.excellent',
    all_entries_correct: 'scenes.S9.S9_D0_F23_C9.all_entries_correct',
    successfully_identified: 'scenes.S9.S9_D0_F23_C9.successfully_identified',
    entries_not_correctly_categorized: 'scenes.S9.S9_D0_F23_C9.entries_not_correctly_categorized',
    incorrect_entries_highlighted: 'scenes.S9.S9_D0_F23_C9.incorrect_entries_highlighted',
    click_entries_see_buttons: 'scenes.S9.S9_D0_F23_C9.click_entries_see_buttons',

    // Categories
    revenue: 'scenes.S9.S9_D0_F23_C9.revenue',
    variable_costs: 'scenes.S9.S9_D0_F23_C9.variable_costs',
    fixed_costs: 'scenes.S9.S9_D0_F23_C9.fixed_costs',
    uncategorized: 'scenes.S9.S9_D0_F23_C9.uncategorized',

    // Button and interaction labels
    move_to_category_options: 'scenes.S9.S9_D0_F23_C9.move_to_category_options',
    move: 'scenes.S9.S9_D0_F23_C9.move',
    to: 'scenes.S9.S9_D0_F23_C9.to',
    category: 'scenes.S9.S9_D0_F23_C9.category',
    button: 'scenes.S9.S9_D0_F23_C9.button',
    of: 'scenes.S9.S9_D0_F23_C9.of',
    revenue_represents_money: 'scenes.S9.S9_D0_F23_C9.revenue_represents_money',
    variable_costs_change: 'scenes.S9.S9_D0_F23_C9.variable_costs_change',
    fixed_costs_remain_constant: 'scenes.S9.S9_D0_F23_C9.fixed_costs_remain_constant',
    move_options_for_item: 'scenes.S9.S9_D0_F23_C9.move_options_for_item',
    from: 'scenes.S9.S9_D0_F23_C9.from',
    remove: 'scenes.S9.S9_D0_F23_C9.remove',
    category_and_return: 'scenes.S9.S9_D0_F23_C9.category_and_return',

    // Screen reader and accessibility
    screen_reader_announcements: 'scenes.S9.S9_D0_F23_C9.screen_reader_announcements',
    date_merchant_ledger_explorer: 'scenes.S9.S9_D0_F23_C9.date_merchant_ledger_explorer',
    instructions_for_screen_reader: 'scenes.S9.S9_D0_F23_C9.instructions_for_screen_reader',
    categorization_game_description: 'scenes.S9.S9_D0_F23_C9.categorization_game_description',
    two_methods_description: 'scenes.S9.S9_D0_F23_C9.two_methods_description',
    check_understanding_instruction: 'scenes.S9.S9_D0_F23_C9.check_understanding_instruction',
    ledger_categorization_interface: 'scenes.S9.S9_D0_F23_C9.ledger_categorization_interface',

    // Main interface elements
    merchants_ledger: 'scenes.S9.S9_D0_F23_C9.merchants_ledger',
    uncategorized_ledger_entries_description: 'scenes.S9.S9_D0_F23_C9.uncategorized_ledger_entries_description',
    entry: 'scenes.S9.S9_D0_F23_C9.entry',
    amount: 'scenes.S9.S9_D0_F23_C9.amount',
    description: 'scenes.S9.S9_D0_F23_C9.description',
    status: 'scenes.S9.S9_D0_F23_C9.status',
    category_buttons_visible: 'scenes.S9.S9_D0_F23_C9.category_buttons_visible',
    press_enter_show_buttons: 'scenes.S9.S9_D0_F23_C9.press_enter_show_buttons',
    press_enter_space_show_buttons: 'scenes.S9.S9_D0_F23_C9.press_enter_space_show_buttons',
    category_selection_buttons: 'scenes.S9.S9_D0_F23_C9.category_selection_buttons',
    all_entries_categorized: 'scenes.S9.S9_D0_F23_C9.all_entries_categorized',
    categories: 'scenes.S9.S9_D0_F23_C9.categories',
    contains: 'scenes.S9.S9_D0_F23_C9.contains',
    items: 'scenes.S9.S9_D0_F23_C9.items',
    drag_entries_here: 'scenes.S9.S9_D0_F23_C9.drag_entries_here',
    items_in: 'scenes.S9.S9_D0_F23_C9.items_in',
    in: 'scenes.S9.S9_D0_F23_C9.in',
    currently_incorrect: 'scenes.S9.S9_D0_F23_C9.currently_incorrect',
    currently_correct: 'scenes.S9.S9_D0_F23_C9.currently_correct',
    press_enter_space_show_move_options: 'scenes.S9.S9_D0_F23_C9.press_enter_space_show_move_options',
    incorrect: 'scenes.S9.S9_D0_F23_C9.incorrect',
    category_move_options: 'scenes.S9.S9_D0_F23_C9.category_move_options',
    no_items_category_yet: 'scenes.S9.S9_D0_F23_C9.no_items_category_yet',

    // Check understanding section
    verify_your_work: 'scenes.S9.S9_D0_F23_C9.verify_your_work',
    check_understanding: 'scenes.S9.S9_D0_F23_C9.check_understanding',
    check_understanding_verify: 'scenes.S9.S9_D0_F23_C9.check_understanding_verify',
    click_button_finished_categorizing: 'scenes.S9.S9_D0_F23_C9.click_button_finished_categorizing',

    // Feedback types
    success: 'scenes.S9.S9_D0_F23_C9.success',
    error: 'scenes.S9.S9_D0_F23_C9.error',
    warning: 'scenes.S9.S9_D0_F23_C9.warning',
  },

  ledgerEntries: [
    {
      id: 1,
      amountKey: 'twelve_dirhams',
      descriptionKey: 'three_pounds_dates_sold',
      category: 'uncategorized',
      correctCategory: 'revenue',
      isWrong: false,
    },
    {
      id: 2,
      amountKey: 'twenty_eight_dirhams',
      descriptionKey: 'seven_pounds_dates_sold',
      category: 'uncategorized',
      correctCategory: 'revenue',
      isWrong: false,
    },
    {
      id: 3,
      amountKey: 'twenty_dirhams',
      descriptionKey: 'five_pounds_dates_sold',
      category: 'uncategorized',
      correctCategory: 'revenue',
      isWrong: false,
    },
    {
      id: 4,
      amountKey: 'twenty_dirhams',
      descriptionKey: 'shop_rent',
      category: 'uncategorized',
      correctCategory: 'fixed',
      isWrong: false,
    },
    {
      id: 5,
      amountKey: 'eighteen_dirhams',
      descriptionKey: 'helper_weekly_wage',
      category: 'uncategorized',
      correctCategory: 'fixed',
      isWrong: false,
    },
    {
      id: 6,
      amountKey: 'forty_two_dirhams',
      descriptionKey: 'date_supply_purchased',
      category: 'uncategorized',
      correctCategory: 'variable',
      isWrong: false,
    },
    {
      id: 7,
      amountKey: 'eight_dirhams',
      descriptionKey: 'storage_baskets',
      category: 'uncategorized',
      correctCategory: 'variable',
      isWrong: false,
    },
    {
      id: 8,
      amountKey: 'twelve_dirhams',
      descriptionKey: 'market_stall_fee',
      category: 'uncategorized',
      correctCategory: 'fixed',
      isWrong: false,
    },
  ],

  categories: [
    { key: 'revenue', color: 'border-green-600' },
    { key: 'variable', color: 'border-yellow-600' },
    { key: 'fixed', color: 'border-red-600' },
  ],
};

export default interactive0Config;
