import { AngleSumExplorerConfig } from '../interface';

const angleSumExplorerConfig: AngleSumExplorerConfig = {
  translations: {
    title: 'scenes.S6.S6_D0_FX_C9.title',
    shape: 'scenes.S6.S6_D0_FX_C9.shape',
    triangle: 'scenes.S6.S6_D0_FX_C9.triangle',
    square: 'scenes.S6.S6_D0_FX_C9.square',
    pentagon: 'scenes.S6.S6_D0_FX_C9.pentagon',
    hexagon: 'scenes.S6.S6_D0_FX_C9.hexagon',
    angleProperties: 'scenes.S6.S6_D0_FX_C9.angleProperties',
    interior: 'scenes.S6.S6_D0_FX_C9.interior',
    exterior: 'scenes.S6.S6_D0_FX_C9.exterior',
    sum: 'scenes.S6.S6_D0_FX_C9.sum',
    testTiling: 'scenes.S6.S6_D0_FX_C9.testTiling',
    perfectTiling: 'scenes.S6.S6_D0_FX_C9.perfectTiling',
    cannotTile: 'scenes.S6.S6_D0_FX_C9.cannotTile',
    copiesPlaced: 'scenes.S6.S6_D0_FX_C9.copiesPlaced',
    totalAngle: 'scenes.S6.S6_D0_FX_C9.totalAngle',
    gapRemaining: 'scenes.S6.S6_D0_FX_C9.gapRemaining',
    perfectFit: 'scenes.S6.S6_D0_FX_C9.perfectFit',
    dragInstructions: 'scenes.S6.S6_D0_FX_C9.dragInstructions',
    canvasAriaLabel: 'scenes.S6.S6_D0_FX_C9.canvasAriaLabel',
    quadDomeAlt: 'scenes.S6.S6_D0_FX_C9.quadDomeAlt',
    // Symbols and formatting
    degreeSymbol: 'scenes.S6.S6_D0_FX_C9.degreeSymbol',
    angleSymbol: 'scenes.S6.S6_D0_FX_C9.angleSymbol',
    successIcon: 'scenes.S6.S6_D0_FX_C9.successIcon',
    failIcon: 'scenes.S6.S6_D0_FX_C9.failIcon',
    vertexLabel: 'scenes.S6.S6_D0_FX_C9.vertexLabel',
    angleLabel: 'scenes.S6.S6_D0_FX_C9.angleLabel',
    // Additional accessibility and UI improvements
    shapeSelectionLabel: 'scenes.S6.S6_D0_FX_C9.shapeSelectionLabel',
    angleDisplayLabel: 'scenes.S6.S6_D0_FX_C9.angleDisplayLabel',
    tilingResultsLabel: 'scenes.S6.S6_D0_FX_C9.tilingResultsLabel',
    stepIndicator: 'scenes.S6.S6_D0_FX_C9.stepIndicator',
    interactiveCanvas: 'scenes.S6.S6_D0_FX_C9.interactiveCanvas',
    visualResult: 'scenes.S6.S6_D0_FX_C9.visualResult',
    // Comprehensive accessibility translations
    keyboardInstructions: 'scenes.S6.S6_D0_FX_C9.keyboardInstructions',
    screenReaderInstructions: 'scenes.S6.S6_D0_FX_C9.screenReaderInstructions',
    focusInstructions: 'scenes.S6.S6_D0_FX_C9.focusInstructions',
    liveAnnouncements: 'scenes.S6.S6_D0_FX_C9.liveAnnouncements',
    errorMessages: 'scenes.S6.S6_D0_FX_C9.errorMessages',
    successMessages: 'scenes.S6.S6_D0_FX_C9.successMessages',
    navigationHelp: 'scenes.S6.S6_D0_FX_C9.navigationHelp',
    canvasInstructions: 'scenes.S6.S6_D0_FX_C9.canvasInstructions',
    vertexInstructions: 'scenes.S6.S6_D0_FX_C9.vertexInstructions',
    angleChangeAnnouncement: 'scenes.S6.S6_D0_FX_C9.angleChangeAnnouncement',
    tilingTestAnnouncement: 'scenes.S6.S6_D0_FX_C9.tilingTestAnnouncement',
    shapeChangeAnnouncement: 'scenes.S6.S6_D0_FX_C9.shapeChangeAnnouncement',
    skipToCanvas: 'scenes.S6.S6_D0_FX_C9.skipToCanvas',
    skipToResults: 'scenes.S6.S6_D0_FX_C9.skipToResults',
    closeInstructions: 'scenes.S6.S6_D0_FX_C9.closeInstructions',
    // Fallback shape name for when shapeNames is not available
    fallbackShapeName: 'scenes.S6.S6_D0_FX_C9.fallbackShapeName',
    // Enhanced accessibility translations
    mainHeading: 'scenes.S6.S6_D0_FX_C9.mainHeading',
    shapeSelectorLabel: 'scenes.S6.S6_D0_FX_C9.shapeSelectorLabel',
    shapeSelectorInstructions: 'scenes.S6.S6_D0_FX_C9.shapeSelectorInstructions',
    angleDisplayInstructions: 'scenes.S6.S6_D0_FX_C9.angleDisplayInstructions',
    tilingButtonInstructions: 'scenes.S6.S6_D0_FX_C9.tilingButtonInstructions',
    resultsInstructions: 'scenes.S6.S6_D0_FX_C9.resultsInstructions',
    canvasDetailedInstructions: 'scenes.S6.S6_D0_FX_C9.canvasDetailedInstructions',
    shapeChangeNotification: 'scenes.S6.S6_D0_FX_C9.shapeChangeNotification',
    angleCalculationNotification: 'scenes.S6.S6_D0_FX_C9.angleCalculationNotification',
    tilingTestStartNotification: 'scenes.S6.S6_D0_FX_C9.tilingTestStartNotification',
    tilingTestCompleteNotification: 'scenes.S6.S6_D0_FX_C9.tilingTestCompleteNotification',
    errorNotification: 'scenes.S6.S6_D0_FX_C9.errorNotification',
    successNotification: 'scenes.S6.S6_D0_FX_C9.successNotification',
    interactiveDescription: 'scenes.S6.S6_D0_FX_C9.interactiveDescription',
    visualDescription: 'scenes.S6.S6_D0_FX_C9.visualDescription',
    mathematicalDescription: 'scenes.S6.S6_D0_FX_C9.mathematicalDescription',
  },
};

export default angleSumExplorerConfig;
