import { QuadrilateralExplorerConfig } from '../interface';

const quadrilateralExplorerConfig: QuadrilateralExplorerConfig = {
  translations: {
    title: 'scenes.S7.S7_D0_FX_C9.title',
    parallelogram: 'scenes.S7.S7_D0_FX_C9.parallelogram',
    rectangle: 'scenes.S7.S7_D0_FX_C9.rectangle',
    rhombus: 'scenes.S7.S7_D0_FX_C9.rhombus',
    square: 'scenes.S7.S7_D0_FX_C9.square',
    quadrilateral: 'scenes.S7.S7_D0_FX_C9.quadrilateral',
    trapezoid: 'scenes.S7.S7_D0_FX_C9.trapezoid',
    isoscelesTrapezoid: 'scenes.S7.S7_D0_FX_C9.isoscelesTrapezoid',
    kite: 'scenes.S7.S7_D0_FX_C9.kite',
    angleSkew: 'scenes.S7.S7_D0_FX_C9.angleSkew',
    sideLengthRatio: 'scenes.S7.S7_D0_FX_C9.sideLengthRatio',
    properties: 'scenes.S7.S7_D0_FX_C9.properties',
    parallelogramDescription: 'scenes.S7.S7_D0_FX_C9.parallelogramDescription',
    rectangleDescription: 'scenes.S7.S7_D0_FX_C9.rectangleDescription',
    rhombusDescription: 'scenes.S7.S7_D0_FX_C9.rhombusDescription',
    squareDescription: 'scenes.S7.S7_D0_FX_C9.squareDescription',
    quadrilateralDescription: 'scenes.S7.S7_D0_FX_C9.quadrilateralDescription',
    trapezoidDescription: 'scenes.S7.S7_D0_FX_C9.trapezoidDescription',
    isoscelesTrapezoidDescription: 'scenes.S7.S7_D0_FX_C9.isoscelesTrapezoidDescription',
    kiteDescription: 'scenes.S7.S7_D0_FX_C9.kiteDescription',
    parallelogramFact1: 'scenes.S7.S7_D0_FX_C9.parallelogramFact1',
    parallelogramFact2: 'scenes.S7.S7_D0_FX_C9.parallelogramFact2',
    parallelogramFact3: 'scenes.S7.S7_D0_FX_C9.parallelogramFact3',
    parallelogramFact4: 'scenes.S7.S7_D0_FX_C9.parallelogramFact4',
    rectangleFact1: 'scenes.S7.S7_D0_FX_C9.rectangleFact1',
    rectangleFact2: 'scenes.S7.S7_D0_FX_C9.rectangleFact2',
    rectangleFact3: 'scenes.S7.S7_D0_FX_C9.rectangleFact3',
    rhombusFact1: 'scenes.S7.S7_D0_FX_C9.rhombusFact1',
    rhombusFact2: 'scenes.S7.S7_D0_FX_C9.rhombusFact2',
    rhombusFact3: 'scenes.S7.S7_D0_FX_C9.rhombusFact3',
    squareFact1: 'scenes.S7.S7_D0_FX_C9.squareFact1',
    squareFact2: 'scenes.S7.S7_D0_FX_C9.squareFact2',
    quadrilateralFact1: 'scenes.S7.S7_D0_FX_C9.quadrilateralFact1',
    quadrilateralFact2: 'scenes.S7.S7_D0_FX_C9.quadrilateralFact2',
    quadrilateralFact3: 'scenes.S7.S7_D0_FX_C9.quadrilateralFact3',
    trapezoidFact1: 'scenes.S7.S7_D0_FX_C9.trapezoidFact1',
    trapezoidFact2: 'scenes.S7.S7_D0_FX_C9.trapezoidFact2',
    isoscelesTrapezoidFact1: 'scenes.S7.S7_D0_FX_C9.isoscelesTrapezoidFact1',
    isoscelesTrapezoidFact2: 'scenes.S7.S7_D0_FX_C9.isoscelesTrapezoidFact2',
    isoscelesTrapezoidFact3: 'scenes.S7.S7_D0_FX_C9.isoscelesTrapezoidFact3',
    isoscelesTrapezoidFact4: 'scenes.S7.S7_D0_FX_C9.isoscelesTrapezoidFact4',
    kiteFact1: 'scenes.S7.S7_D0_FX_C9.kiteFact1',
    kiteFact2: 'scenes.S7.S7_D0_FX_C9.kiteFact2',
    kiteFact3: 'scenes.S7.S7_D0_FX_C9.kiteFact3',
    canvasAriaLabel: 'scenes.S7.S7_D0_FX_C9.canvasAriaLabel',
    // Units and symbols
    degreeSymbol: 'scenes.S7.S7_D0_FX_C9.degreeSymbol',
    // Dynamic content templates
    angleLabel: 'scenes.S7.S7_D0_FX_C9.angleLabel',
    ratioLabel: 'scenes.S7.S7_D0_FX_C9.ratioLabel',
    // Vertex labels
    vertexA: 'scenes.S7.S7_D0_FX_C9.vertexA',
    vertexB: 'scenes.S7.S7_D0_FX_C9.vertexB',
    vertexC: 'scenes.S7.S7_D0_FX_C9.vertexC',
    vertexD: 'scenes.S7.S7_D0_FX_C9.vertexD',
    // Shape type names for dynamic calculations
    shapeTypeSquare: 'scenes.S7.S7_D0_FX_C9.shapeTypeSquare',
    shapeTypeRectangle: 'scenes.S7.S7_D0_FX_C9.shapeTypeRectangle',
    shapeTypeRhombus: 'scenes.S7.S7_D0_FX_C9.shapeTypeRhombus',
    shapeTypeParallelogram: 'scenes.S7.S7_D0_FX_C9.shapeTypeParallelogram',
    // Accessibility translations
    srInstructions: 'scenes.S7.S7_D0_FX_C9.srInstructions',
    srShapeSelected: 'scenes.S7.S7_D0_FX_C9.srShapeSelected',
    srAngleChanged: 'scenes.S7.S7_D0_FX_C9.srAngleChanged',
    srRatioChanged: 'scenes.S7.S7_D0_FX_C9.srRatioChanged',
    srShapeTransformed: 'scenes.S7.S7_D0_FX_C9.srShapeTransformed',
    srCanvasDescription: 'scenes.S7.S7_D0_FX_C9.srCanvasDescription',
    srPropertiesDescription: 'scenes.S7.S7_D0_FX_C9.srPropertiesDescription',
    srSliderInstructions: 'scenes.S7.S7_D0_FX_C9.srSliderInstructions',
    srButtonInstructions: 'scenes.S7.S7_D0_FX_C9.srButtonInstructions',
    srCurrentShape: 'scenes.S7.S7_D0_FX_C9.srCurrentShape',
    srAngleValue: 'scenes.S7.S7_D0_FX_C9.srAngleValue',
    srRatioValue: 'scenes.S7.S7_D0_FX_C9.srRatioValue',
    srDisabledSliders: 'scenes.S7.S7_D0_FX_C9.srDisabledSliders',
    srEnabledSliders: 'scenes.S7.S7_D0_FX_C9.srEnabledSliders',
    // Boolean values for accessibility
    yes: 'scenes.S7.S7_D0_FX_C9.yes',
    no: 'scenes.S7.S7_D0_FX_C9.no',
    // Enhanced accessibility translations
    mainHeading: 'scenes.S7.S7_D0_FX_C9.mainHeading',
    shapeSelectorLabel: 'scenes.S7.S7_D0_FX_C9.shapeSelectorLabel',
    shapeSelectorInstructions: 'scenes.S7.S7_D0_FX_C9.shapeSelectorInstructions',
    sliderControlsLabel: 'scenes.S7.S7_D0_FX_C9.sliderControlsLabel',
    sliderControlsInstructions: 'scenes.S7.S7_D0_FX_C9.sliderControlsInstructions',
    canvasSectionLabel: 'scenes.S7.S7_D0_FX_C9.canvasSectionLabel',
    canvasSectionInstructions: 'scenes.S7.S7_D0_FX_C9.canvasSectionInstructions',
    propertiesSectionLabel: 'scenes.S7.S7_D0_FX_C9.propertiesSectionLabel',
    propertiesSectionInstructions: 'scenes.S7.S7_D0_FX_C9.propertiesSectionInstructions',
    interactiveDescription: 'scenes.S7.S7_D0_FX_C9.interactiveDescription',
    visualDescription: 'scenes.S7.S7_D0_FX_C9.visualDescription',
    mathematicalDescription: 'scenes.S7.S7_D0_FX_C9.mathematicalDescription',
    shapeChangeNotification: 'scenes.S7.S7_D0_FX_C9.shapeChangeNotification',
    angleChangeNotification: 'scenes.S7.S7_D0_FX_C9.angleChangeNotification',
    ratioChangeNotification: 'scenes.S7.S7_D0_FX_C9.ratioChangeNotification',
    sliderEnabledNotification: 'scenes.S7.S7_D0_FX_C9.sliderEnabledNotification',
    sliderDisabledNotification: 'scenes.S7.S7_D0_FX_C9.sliderDisabledNotification',
    errorNotification: 'scenes.S7.S7_D0_FX_C9.errorNotification',
    successNotification: 'scenes.S7.S7_D0_FX_C9.successNotification',
  },
};

export default quadrilateralExplorerConfig;
