import { DialogPosition, DialogWidth, LogoTheme, SCENE_CHANGE_DELAY } from '../../constants/constants';
import { SceneData } from '../../types/interfaces';

export const sceneData: SceneData[] = [
  // Start Scene
  {
    name: 'scenesList.scene_1',
    background: {
      alt: 'scenes.common.bg1_description',
      url: '/assets/backgrounds/bg1.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      initialZoom: 1.0,
    },
    logoTheme: {
      landscape: LogoTheme.LIGHT,
      portrait: LogoTheme.LIGHT,
    },
    audioUrl: '/assets/audio/bgmusic.mp3',
    type: 'one-at-a-time',
    dialogs: [
      {
        heading: 'start.title',
        body: 'start.description',
        headingColor: '#333333',
        disableAnimation: true,
        position: {
          left: DialogPosition.START_SCREEN_LEFT,
          top: DialogPosition.START_SCREEN_TOP,
        },
        width: DialogWidth.START_SCREEN,
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: 'scenes.common.nina_description',
          size: 'chat-bubble-square',
          background: '#6FE9FF',
        },
        controls: [
          {
            type: 'start',
            text: 'start.start_game',
          },
        ],
        background: {
          blur: 16,
          zoom: 1.15,
          pan: 650,
        },
      },
    ],
  },

  // Scene 2
  {
    name: 'scenesList.scene_2',
    background: {
      alt: 'scenes.common.bg2_description',
      url: '/assets/backgrounds/bg2.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      initialZoom: 1.15,
      pan: 435,
      blur: 15,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        heading: 'scenes.S2.S2_D1_FX_C0.heading',
        bodyAsHtml: 'scenes.S2.S2_D1_FX_C0.body',
        headingColor: '#333333',
        isPrimaryHeading: true,
        disableAnimation: true,
        position: {
          top: '50%',
          left: '50%',
        },
        background: {
          blur: 15,
          zoom: 1.15,
          pan: 435,
        },
        glossary: [
          {
            word: 'scenes.glossary.mathematical_modeling.word',
            definitionAsHtml: 'scenes.glossary.mathematical_modeling.definition',
          },
        ],
        width: '80.5vw',
        audioUrl: '/assets/audio/get-in-the-zone_S2_D1_FX_C0_en.mp3',
      },
    ],
  },

  // Scene 3
  {
    name: 'scenesList.scene_3',
    background: {
      alt: 'scenes.common.bg2_description',
      url: '/assets/backgrounds/bg2.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 15.5,
      zoom: 1.15,
      pan: 260,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        disableAnimation: true,
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S3.S3_D1_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37.5%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D1_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S3.S3_D2_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: 'scenes.common.rivera_description',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D2_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S3.S3_D3_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37.5%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D3_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S3.S3_D4_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D4_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S3.S3_D5_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D5_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S3.S3_D6_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D6_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S3.S3_D7_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D7_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S3.S3_D8_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D8_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S3.S3_D9_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D9_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S3.S3_D10_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        glossary: [
          {
            word: 'scenes.glossary.performance_range.word',
            definitionAsHtml: 'scenes.glossary.performance_range.definition',
          },
        ],
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D10_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S3.S3_D11_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D11_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S3.S3_D12_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        glossary: [
          {
            word: 'scenes.glossary.performance_range.word',
            definitionAsHtml: 'scenes.glossary.performance_range.definition',
          },
        ],
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S3_D12_FX_C1_en.mp3',
      },
    ],
  },

  // Scene 6
  {
    name: 'scenesList.scene_4',
    background: {
      url: '/assets/backgrounds/bg3.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 14,
      zoom: 1.25,
      pan: 50,
    },
    type: 'split-screen-chat',
    leftConfig: {
      blur: 0,
      background: 'rgba(255, 255, 255, 0.4)',
    },
    dialogs: [
      {
        side: 'left',
        skipNavigation: true,
        heading: 'scenes.S6.S6_D0_F20_C9.title',
        interactions: [
          {
            name: 'interactive-1',
            config: 'interactive-1',
            enableStateExchange: true,
          },
        ],
        headingColor: '#333',
        isPrimaryHeading: true,
        position: { left: '24.3%', bottom: '6.25%' },
        background: {
          blur: 20,
          pan: 0,
        },
        about: [
          {
            heading: 'scenes.S6.S6_D0_F20_C9.about.heading',
            bodyAsHtml: 'scenes.S6.S6_D0_F20_C9.about.body',
            accentColor: '#006BE0',
          },
        ],
        help: [
          {
            heading: 'scenes.S6.S6_D0_F20_C9.help.heading',
            bodyAsHtml: 'scenes.S6.S6_D0_F20_C9.help.body',
            accentColor: '#A22DDC',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S6.S6_D1_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D1_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S6.S6_D2_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        events: [
          {
            payload: {
              target: 'interactive-1',
              disabled: 'interactive-1-step-0-completion',
            },
            triggers: ['on-next', 'on-back'],
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S6_D2_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S6.S6_D3_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D3_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S6.S6_D4_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D4_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S6.S6_D5_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D5_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S6.S6_D6_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        interactions: [
          {
            name: 'interactive-inputbox',
            config: 'question-itr1-improvements',
          },
        ],
        controls: [
          {
            type: 'back',
            text: 'dialog.button.back',
          },
          {
            type: 'submit',
            text: 'dialog.button.submit',
          },
        ],
        glossary: [
          {
            word: 'scenes.glossary.performance_range.word',
            definitionAsHtml: 'scenes.glossary.performance_range.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S6_D6_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S6.S6_D7_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D7_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S6.S6_D8_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D8_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S6.S6_D9_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D9_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S6.S6_D10_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D10_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S6.S6_D11_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D11_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S6.S6_D12_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S6_D12_FX_C1_en.mp3',
      },
    ],
  },

  // Scene 7
  {
    name: 'scenesList.scene_5',
    background: {
      alt: 'scenes.common.bg3_description',
      url: '/assets/backgrounds/bg3.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 15.5,
      zoom: 1.15,
      pan: 200,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        heading: 'scenes.common.nina',
        isPrimaryHeading: true,
        bodyAsHtml: 'scenes.S7.S7_D1_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D1_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S7.S7_D2_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '54%',
          left: '62.5%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '57vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D2_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S7.S7_D3_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D3_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S7.S7_D4_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '54%',
          left: '62.5%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '57vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D4_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S7.S7_D5_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '54%',
          left: '62.5%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '57vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D5_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S7.S7_D6_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D6_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S7.S7_D7_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '54%',
          left: '62.5%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '57vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D7_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S7.S7_D8_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D8_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S7.S7_D9_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '54%',
          left: '62.5%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '57vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D9_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S7.S7_D10_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D10_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S7.S7_D11_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '54%',
          left: '62.5%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        glossary: [
          {
            word: 'scenes.glossary.literal_equation.word',
            definitionAsHtml: 'scenes.glossary.literal_equation.definition',
          },
        ],
        width: '57vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D11_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S7.S7_D12_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D12_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S7.S7_D13_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S7_D13_FX_C1_en.mp3',
      },
    ],
  },

  // Scene 8
  {
    name: 'scenesList.scene_6',
    background: {
      alt: 'scenes.common.bg2_description',
      url: '/assets/backgrounds/bg2.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 15,
      zoom: 1.2,
      pan: 710,
    },
    type: 'split-screen-chat',
    leftConfig: {
      blur: 0,
      background: 'rgba(255, 255, 255, 0.4)',
    },
    dialogs: [
      {
        side: 'left',
        skipNavigation: true,
        isPrimaryHeading: true,
        heading: 'scenes.S8.S8_D0_F42_C9.header.title',
        interactions: [
          {
            name: 'interactive-2',
            config: 'interactive-2',
            enableStateExchange: true,
          },
        ],
        headingColor: '#333',
        about: [
          {
            heading: 'scenes.S8.S8_D0_F42_C9.about.heading',
            bodyAsHtml: 'scenes.S8.S8_D0_F42_C9.about.body',
            accentColor: '#006BE0',
          },
        ],
        help: [
          {
            heading: 'scenes.S8.S8_D0_F42_C9.help.heading',
            bodyAsHtml: 'scenes.S8.S8_D0_F42_C9.help.body',
            accentColor: '#A22DDC',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D1_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        events: [
          {
            payload: {
              target: 'interactive-2',
              step: 0,
            },
            triggers: ['on-next', 'on-back'],
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S8_D1_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S8.S8_D2_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D2_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D3_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        events: [
          {
            payload: {
              target: 'interactive-2',
              disabled: 'interactive-2-step-0-completion',
            },
            triggers: ['on-next', 'on-back'],
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S8_D3_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S8.S8_D4_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D4_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D5_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D5_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S8.S8_D6_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        events: [
          {
            payload: {
              target: 'interactive-2',
              step: 0,
            },
            triggers: ['on-next', 'on-back'],
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S8_D6_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D7_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        events: [
          {
            payload: {
              target: 'interactive-2',
              step: 1,
            },
            triggers: ['on-next', 'on-back'],
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S8_D7_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D8_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        interactions: [
          {
            name: 'interactive-inputbox',
            config: 'question-itr2-third-segment',
          },
        ],
        controls: [
          {
            type: 'back',
            text: 'dialog.button.back',
          },
          {
            type: 'submit',
            text: 'dialog.button.submit',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S8_D8_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S8.S8_D9_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D9_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D10_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D10_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S8.S8_D11_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D11_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D12_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D12_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D13_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        interactions: [
          {
            name: 'interactive-radio',
            config: 'question-itr2-time-segment',
          },
        ],
        controls: [
          {
            type: 'back',
            text: 'dialog.button.back',
          },
          {
            type: 'submit',
            text: 'dialog.button.submit',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S8_D13_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S8.S8_D14_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D14_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D15_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D15_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S8.S8_D16_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.distance_formula.word',
            definitionAsHtml: 'scenes.glossary.distance_formula.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S8_D16_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S8.S8_D17_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S8_D17_FX_C1_en.mp3',
      },
    ],
  },

  // Scene 9
  {
    name: 'scenesList.scene_7',
    background: {
      alt: 'scenes.common.bg2_description',
      url: '/assets/backgrounds/bg2.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 15.5,
      zoom: 1.15,
      pan: 260,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        disableAnimation: true,
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S9.S9_D1_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37.5%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D1_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S9.S9_D2_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D2_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S9.S9_D3_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D3_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S9.S9_D4_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        glossary: [
          {
            word: 'scenes.glossary.training_effect_threshold.word',
            definitionAsHtml: 'scenes.glossary.training_effect_threshold.definition',
          },
        ],
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D4_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S9.S9_D5_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D5_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S9.S9_D6_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        glossary: [
          {
            word: 'scenes.glossary.compound_inequality.word',
            definitionAsHtml: 'scenes.glossary.compound_inequality.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S9_D6_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S9.S9_D7_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D7_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S9.S9_D8_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        glossary: [
          {
            word: 'scenes.glossary.compound_inequalities.word',
            definitionAsHtml: 'scenes.glossary.compound_inequalities.definition',
          },
        ],
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D8_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S9.S9_D9_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37%',
        },
        avatar: {
          src: '/assets/characters/char2.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        glossary: [
          {
            word: 'scenes.glossary.compound_inequalities.word',
            definitionAsHtml: 'scenes.glossary.compound_inequalities.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S9_D9_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S9.S9_D10_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D10_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S9.S9_D11_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37.5%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D11_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S9.S9_D12_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S9_D12_FX_C1_en.mp3',
      },
    ],
  },

  // Scene 10
  {
    name: 'scenesList.scene_8',
    background: {
      alt: 'scenes.common.bg3_description',
      url: '/assets/backgrounds/bg3.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 14,
      zoom: 1.25,
      pan: 30,
    },
    type: 'split-screen-chat',
    leftConfig: {
      blur: 0,
      background: 'rgba(255, 255, 255, 0.4)',
    },
    dialogs: [
      {
        side: 'left',
        skipNavigation: true,
        isPrimaryHeading: true,
        heading: 'scenes.S10.S10_D0_F60_C9.header.title',
        interactions: [
          {
            name: 'interactive-3',
            config: 'interactive-3',
          },
        ],
        headingColor: '#000',
        position: { left: '24.3%', bottom: '6.25%' },
        background: {
          blur: 20,
          pan: 0,
        },
        about: [
          {
            heading: 'scenes.S10.S10_D0_F60_C9.about.heading',
            bodyAsHtml: 'scenes.S10.S10_D0_F60_C9.about.body',
            accentColor: '#006BE0',
          },
        ],
        help: [
          {
            heading: 'scenes.S10.S10_D0_F60_C9.help.heading',
            bodyAsHtml: 'scenes.S10.S10_D0_F60_C9.help.body',
            accentColor: '#A22DDC',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D1_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D1_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S10.S10_D2_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D2_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D3_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D3_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D4_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.compound_inequality.word',
            definitionAsHtml: 'scenes.glossary.compound_inequality.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S10_D4_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S10.S10_D5_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.compound_inequality.word',
            definitionAsHtml: 'scenes.glossary.compound_inequality.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S10_D5_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D6_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.compound_inequality.word',
            definitionAsHtml: 'scenes.glossary.compound_inequality.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S10_D6_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D7_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        interactions: [
          {
            name: 'interactive-range-inputbox',
            config: 'question-itr3-bound-speed',
          },
        ],
        controls: [
          {
            type: 'back',
            text: 'dialog.button.back',
          },
          {
            type: 'submit',
            text: 'dialog.button.submit',
          },
        ],
        glossary: [
          {
            word: 'scenes.glossary.compound_inequality.word',
            definitionAsHtml: 'scenes.glossary.compound_inequality.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S10_D7_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S10.S10_D8_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D8_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D9_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D9_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S10.S10_D10_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D10_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D11_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D11_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D12_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        interactions: [
          {
            name: 'interactive-radio',
            config: 'question-itr3-compund-inequality',
          },
        ],
        controls: [
          {
            type: 'back',
            text: 'dialog.button.back',
          },
          {
            type: 'submit',
            text: 'dialog.button.submit',
          },
        ],
        glossary: [
          {
            word: 'scenes.glossary.compound_inequality.word',
            definitionAsHtml: 'scenes.glossary.compound_inequality.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S10_D12_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S10.S10_D13_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D13_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D14_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.compound_inequalities.word',
            definitionAsHtml: 'scenes.glossary.compound_inequalities.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S10_D14_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S10.S10_D15_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D15_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D16_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.distance_formula.word',
            definitionAsHtml: 'scenes.glossary.distance_formula.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S10_D16_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D17_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        interactions: [
          {
            name: 'interactive-range-inputbox',
            config: 'question-itr3-bound-time',
          },
        ],
        controls: [
          {
            type: 'back',
            text: 'dialog.button.back',
          },
          {
            type: 'submit',
            text: 'dialog.button.submit',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S10_D17_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S10.S10_D18_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D18_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D19_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D19_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S10.S10_D20_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D20_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D21_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.compound_inequalities.word',
            definitionAsHtml: 'scenes.glossary.compound_inequalities.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S10_D21_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S10.S10_D22_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D22_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S10.S10_D23_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S10_D23_FX_C1_en.mp3',
      },
    ],
  },

  //Scene 11
  {
    name: 'scenesList.scene_9',
    background: {
      alt: 'scenes.common.bg2_description',
      url: '/assets/backgrounds/bg2.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 15.5,
      zoom: 1.15,
      pan: 260,
    },
    type: 'one-at-a-time',
    dialogs: [
      {
        disableAnimation: true,
        heading: 'scenes.common.nina',
        isPrimaryHeading: true,
        bodyAsHtml: 'scenes.S11.S11_D1_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37.5%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S11_D1_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S11.S11_D2_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '53%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S11_D2_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S11.S11_D3_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37.5%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S11_D3_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S11.S11_D4_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '55%',
          left: '62%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S11_D4_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S11.S11_D5_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37.5%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S11_D5_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S11.S11_D6_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '55%',
          left: '64%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        glossary: [
          {
            word: 'scenes.glossary.absolute_value.word',
            definitionAsHtml: 'scenes.glossary.absolute_value.definition',
          },
        ],
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S11_D6_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S11.S11_D7_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37.5%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S11_D7_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S11.S11_D8_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '55%',
          left: '64%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        glossary: [
          {
            word: 'scenes.glossary.race_day_factor.word',
            definitionAsHtml: 'scenes.glossary.race_day_factor.definition',
          },
        ],
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S11_D8_FX_C1_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S11.S11_D9_FX_C2',
        headingColor: '#4700E0',
        position: {
          top: '55%',
          left: '37.5%',
        },
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'large',
          position: 'right',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutRight',
          },
        },
        width: '56vw',
        audioUrl: '/assets/audio/get-in-the-zone_S11_D9_FX_C2_en.mp3',
      },
      {
        isPrimaryHeading: true,
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S11.S11_D10_FX_C1',
        headingColor: '#CA16D6',
        position: {
          top: '55%',
          left: '64%',
        },
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'large',
          position: 'left',
          animation: {
            duration: 300,
            delay: 0,
            entry: 'fadeIn',
            exit: 'fadeOutLeft',
          },
        },
        width: '56vw',
        glossary: [
          {
            word: 'scenes.glossary.mathematical_modeling.word',
            definitionAsHtml: 'scenes.glossary.mathematical_modeling.definition',
          },
          {
            word: 'scenes.glossary.race_day_factor.word',
            definitionAsHtml: 'scenes.glossary.race_day_factor.definition',
          },
          {
            word: 'scenes.glossary.performance_range.word',
            definitionAsHtml: 'scenes.glossary.performance_range.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S11_D10_FX_C1_en.mp3',
      },
    ],
  },

  // Scene 12
  {
    name: 'scenesList.scene_10',
    background: {
      alt: 'scenes.common.bg3_description',
      url: '/assets/backgrounds/bg3.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      blur: 14,
      zoom: 1.25,
      pan: 30,
    },
    type: 'split-screen-chat',
    leftConfig: {
      blur: 0,
      background: 'rgba(255, 255, 255, 0.4)',
    },
    dialogs: [
      {
        side: 'left',
        skipNavigation: true,
        heading: 'scenes.S12.S12_D0_F80_C9.header.title',
        interactions: [
          {
            name: 'interactive-4',
            config: 'interactive-4',
          },
        ],
        isPrimaryHeading: true,
        headingColor: '#000',
        position: { left: '24.3%', bottom: '6.25%' },
        about: [
          {
            heading: 'scenes.S12.S12_D0_F80_C9.about.heading',
            bodyAsHtml: 'scenes.S12.S12_D0_F80_C9.about.body',
            accentColor: '#006BE0',
          },
        ],
        help: [
          {
            heading: 'scenes.S12.S12_D0_F80_C9.help.heading',
            bodyAsHtml: 'scenes.S12.S12_D0_F80_C9.help.body',
            accentColor: '#A22DDC',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S12.S12_D1_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S12_D1_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S12.S12_D2_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S12_D2_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S12.S12_D3_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.performance_variability.word',
            definitionAsHtml: 'scenes.glossary.performance_variability.definition',
          },
          {
            word: 'scenes.glossary.baseline_prediction.word',
            definitionAsHtml: 'scenes.glossary.baseline_prediction.definition',
          },
          {
            word: 'scenes.glossary.race_day_factor.word',
            definitionAsHtml: 'scenes.glossary.race_day_factor.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S12_D3_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S12.S12_D4_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.race_day_factor.word',
            definitionAsHtml: 'scenes.glossary.race_day_factor.definition',
          },
          {
            word: 'scenes.glossary.absolute_value.word',
            definitionAsHtml: 'scenes.glossary.absolute_value.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S12_D4_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S12.S12_D5_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.heart_rate.word',
            definitionAsHtml: 'scenes.glossary.heart_rate.definition',
          },
          {
            word: 'scenes.glossary.absolute_value_inequality.word',
            definitionAsHtml: 'scenes.glossary.absolute_value_inequality.definition',
          },
          {
            word: 'scenes.glossary.absolute_value.word',
            definitionAsHtml: 'scenes.glossary.absolute_value.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S12_D5_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S12.S12_D6_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        interactions: [
          {
            name: 'interactive-inputbox',
            config: 'question-itr4-wrost-time',
          },
        ],
        controls: [
          {
            type: 'back',
            text: 'dialog.button.back',
          },
          {
            type: 'submit',
            text: 'dialog.button.submit',
          },
        ],
        glossary: [
          {
            word: 'scenes.glossary.race_day_factor.word',
            definitionAsHtml: 'scenes.glossary.race_day_factor.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S12_D6_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S12.S12_D7_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.baseline_prediction.word',
            definitionAsHtml: 'scenes.glossary.baseline_prediction.definition',
          },
          {
            word: 'scenes.glossary.race_day_factor.word',
            definitionAsHtml: 'scenes.glossary.race_day_factor.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S12_D7_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S12.S12_D8_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S12_D8_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S12.S12_D9_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S12_D9_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S12.S12_D17_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.absolute_value_inequality.word',
            definitionAsHtml: 'scenes.glossary.absolute_value_inequality.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S12_D17_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S12.S12_D18_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S12_D18_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S12.S12_D19_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        glossary: [
          {
            word: 'scenes.glossary.mathematical_modeling.word',
            definitionAsHtml: 'scenes.glossary.mathematical_modeling.definition',
          },
        ],
        audioUrl: '/assets/audio/get-in-the-zone_S12_D19_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S12.S12_D20_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S12_D20_FX_C2_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.rivera',
        body: 'scenes.S12.S12_D21_FX_C1',
        headingColor: '#CA16D6',
        avatar: {
          src: '/assets/characters/char1mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#FBC0FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S12_D21_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        body: 'scenes.S12.S12_D22_FX_C2',
        headingColor: '#4700E0',
        avatar: {
          src: '/assets/characters/char2mini.webp',
          alt: '',
          size: 'chat-bubble',
          background: '#AEA8FF',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S12_D22_FX_C2_en.mp3',
      },
    ],
  },

  // Scene 13
  {
    name: 'scenesList.scene_11',
    background: {
      alt: 'scenes.common.bg4_description',
      url: '/assets/backgrounds/bg4.webp',
      pan: 730,
      zoom: 1.075,
      blur: 16,
      waitDelay: SCENE_CHANGE_DELAY,
    },
    type: 'turn-based-chat',
    dialogs: [
      {
        isPrimaryHeading: true,
        side: 'left',
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S13.S13_D1_FX_C1',
        headingColor: '#A22DDC',
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'enlarged',
          position: 'left',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S13_D1_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S13.S13_D2_FX_C2',
        headingColor: '#006BE0',
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'enlarged',
          position: 'right',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S13_D2_FX_C2_en.mp3',
      },
      {
        side: 'left',
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S13.S13_D3_FX_C1',
        headingColor: '#A22DDC',
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'enlarged',
          position: 'left',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S13_D3_FX_C1_en.mp3',
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S13.S13_D4_FX_C2',
        headingColor: '#006BE0',
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'enlarged',
          position: 'right',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S13_D4_FX_C2_en.mp3',
        glossary: [
          {
            word: 'scenes.glossary.heart_rate.word',
            definitionAsHtml: 'scenes.glossary.heart_rate.definition',
          },
          {
            word: 'scenes.glossary.maximum_heart_rate.word',
            definitionAsHtml: 'scenes.glossary.maximum_heart_rate.definition',
          },
        ],
      },
      {
        side: 'left',
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S13.S13_D5_FX_C1',
        headingColor: '#A22DDC',
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'enlarged',
          position: 'left',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S13_D5_FX_C1_en.mp3',
        glossary: [
          {
            word: 'scenes.glossary.training_zones.word',
            definitionAsHtml: 'scenes.glossary.training_zones.definition',
          },
          {
            word: 'scenes.glossary.inequalities.word',
            definitionAsHtml: 'scenes.glossary.inequalities.definition',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S13.S13_D6_FX_C2',
        headingColor: '#006BE0',
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'enlarged',
          position: 'right',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S13_D6_FX_C2_en.mp3',
        glossary: [
          {
            word: 'scenes.glossary.pace.word',
            definitionAsHtml: 'scenes.glossary.pace.definition',
          },
        ],
      },
      {
        side: 'left',
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S13.S13_D7_FX_C1',
        headingColor: '#A22DDC',
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'enlarged',
          position: 'left',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S13_D7_FX_C1_en.mp3',
        glossary: [
          {
            word: 'scenes.glossary.pace.word',
            definitionAsHtml: 'scenes.glossary.pace.definition',
          },
        ],
      },
      {
        side: 'right',
        heading: 'scenes.common.nina',
        bodyAsHtml: 'scenes.S13.S13_D8_FX_C2',
        headingColor: '#006BE0',
        avatar: {
          src: '/assets/characters/char2long.webp',
          alt: '',
          size: 'enlarged',
          position: 'right',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S13_D8_FX_C2_en.mp3',
        glossary: [
          {
            word: 'scenes.glossary.absolute_value.word',
            definitionAsHtml: 'scenes.glossary.absolute_value.definition',
          },
          {
            word: 'scenes.glossary.performance_ranges.word',
            definitionAsHtml: 'scenes.glossary.performance_ranges.definition',
          },
        ],
      },
      {
        side: 'left',
        heading: 'scenes.common.rivera',
        bodyAsHtml: 'scenes.S13.S13_D9_FX_C1',
        headingColor: '#A22DDC',
        avatar: {
          src: '/assets/characters/char1long.webp',
          alt: '',
          size: 'enlarged',
          position: 'left',
        },
        audioUrl: '/assets/audio/get-in-the-zone_S13_D9_FX_C1_en.mp3',
        glossary: [
          {
            word: 'scenes.glossary.compound_inequalities.word',
            definitionAsHtml: 'scenes.glossary.compound_inequalities.definition',
          },
          {
            word: 'scenes.glossary.absolute_value.word',
            definitionAsHtml: 'scenes.glossary.absolute_value.definition',
          },
        ],
      },
    ],
  },

  // End Scene
  {
    name: 'scenesList.scene_12',
    background: {
      alt: 'scenes.common.bg4_description',
      url: '/assets/backgrounds/EndScreen.webp',
      waitDelay: SCENE_CHANGE_DELAY,
      pan: 1215,
      zoom: 1.1,
      blur: 14,
    },
    type: 'end-screen',
    showConfetti: true,
    dialogs: [
      {
        heading: 'scenes.S14.S14_D1_F104_C9',
        body: 'scenes.S14.S14_D2_F104_C9',
        headingColor: '#333333',
        disableAnimation: true,
        position: { left: '50%', top: '50%' },
        width: '80vw',
        avatar: {
          src: '/assets/icons/sportswoman.webp',
          alt: 'sportswoman',
          size: 'chat-bubble-square',
          background: '#6FE9FF',
        },
        controls: [
          {
            type: 'back',
            text: 'dialog.button.back',
          },
          {
            type: 'start',
            text: 'dialog.button.start_again',
          },
        ],
        background: {
          blur: 16,
          zoom: 1.1,
          pan: 725,
        },
        glossary: [
          {
            word: 'scenes.glossary.inequalities.word',
            definitionAsHtml: 'scenes.glossary.inequalities.definition',
          },
          {
            word: 'scenes.glossary.compound_inequalities.word',
            definitionAsHtml: 'scenes.glossary.compound_inequalities.definition',
          },
          {
            word: 'scenes.glossary.heart_rate.word',
            definitionAsHtml: 'scenes.glossary.heart_rate.definition',
          },
          {
            word: 'scenes.glossary.training_zones.word',
            definitionAsHtml: 'scenes.glossary.training_zones.definition',
          },
          {
            word: 'scenes.glossary.absolute_value.word',
            definitionAsHtml: 'scenes.glossary.absolute_value.definition',
          },
          {
            word: 'scenes.glossary.pace.word',
            definitionAsHtml: 'scenes.glossary.pace.definition',
          },
          {
            word: 'scenes.glossary.performance_ranges.word',
            definitionAsHtml: 'scenes.glossary.performance_ranges.definition',
          },
        ],
      },
    ],
  },
];
