const interaction = {
  musicalInterval: 'scenes.S5.S5_D0_FX_C9.interactive_data.musicalInterval',
  playText: 'scenes.S5.S5_D0_FX_C9.interactive_data.playText',
  octaveModeText: 'scenes.S5.S5_D0_FX_C9.interactive_data.octaveModeText',
  perfectFifthModeText: 'scenes.S5.S5_D0_FX_C9.interactive_data.perfectFifthModeText',
  modeText: 'scenes.S5.S5_D0_FX_C9.interactive_data.modeText',
  toggleText: 'scenes.S5.S5_D0_FX_C9.interactive_data.toggleText',
  frequencyRatioText: 'scenes.S5.S5_D0_FX_C9.interactive_data.frequencyRatioText',
  simplifiedRatioText: 'scenes.S5.S5_D0_FX_C9.interactive_data.simplifiedRatioText',
  playSequence: 'scenes.S5.S5_D0_FX_C9.interactive_data.playSequence',
  noteA: 'scenes.S5.S5_D0_FX_C9.interactive_data.noteA',
  noteE: 'scenes.S5.S5_D0_FX_C9.interactive_data.noteE',
  noteAPrime: 'scenes.S5.S5_D0_FX_C9.interactive_data.noteAPrime',
  hertz: 'scenes.S5.S5_D0_FX_C9.interactive_data.hertz',
  sequenceComplete: 'scenes.S5.S5_D0_FX_C9.interactive_data.sequenceComplete',
  playNoteA: 'scenes.S5.S5_D0_FX_C9.interactive_data.playNoteA',
  playNoteE: 'scenes.S5.S5_D0_FX_C9.interactive_data.playNoteE',
  playNoteAPrime: 'scenes.S5.S5_D0_FX_C9.interactive_data.playNoteAPrime',
  pianoKeysLabel: 'scenes.S5.S5_D0_FX_C9.interactive_data.pianoKeysLabel',
  playingNoteA: 'scenes.S5.S5_D0_FX_C9.interactive_data.playingNoteA',
  playingNoteE: 'scenes.S5.S5_D0_FX_C9.interactive_data.playingNoteE',
  playingNoteAPrime: 'scenes.S5.S5_D0_FX_C9.interactive_data.playingNoteAPrime',
  playingBothOctave: 'scenes.S5.S5_D0_FX_C9.interactive_data.playingBothOctave',
  playingBothFifth: 'scenes.S5.S5_D0_FX_C9.interactive_data.playingBothFifth',
  switchedToOctave: 'scenes.S5.S5_D0_FX_C9.interactive_data.switchedToOctave',
  switchedToFifth: 'scenes.S5.S5_D0_FX_C9.interactive_data.switchedToFifth',
  playingOctaveSequence: 'scenes.S5.S5_D0_FX_C9.interactive_data.playingOctaveSequence',
  playingFifthSequence: 'scenes.S5.S5_D0_FX_C9.interactive_data.playingFifthSequence',
  visualizationDescription: 'scenes.S5.S5_D0_FX_C9.interactive_data.visualizationDescription',
  octaveRatioDescription: 'scenes.S5.S5_D0_FX_C9.interactive_data.octaveRatioDescription',
  fifthRatioDescription: 'scenes.S5.S5_D0_FX_C9.interactive_data.fifthRatioDescription',
};

export default interaction;
