const interaction = {
  forText: 'scenes.S7.S7_D0_F40_C9.interactive_data.forText',
  approximationErrorText: 'scenes.S7.S7_D0_F40_C9.interactive_data.approximationErrorText',
  closestIntegerText: 'scenes.S7.S7_D0_F40_C9.interactive_data.closestIntegerText',
  errorText: 'scenes.S7.S7_D0_F40_C9.interactive_data.errorText',
  sliderHeading: 'scenes.S7.S7_D0_F40_C9.interactive_data.sliderHeading',
  stepInOctaveText: 'scenes.S7.S7_D0_F40_C9.interactive_data.stepInOctaveText',
  excellentChoiceText: 'scenes.S7.S7_D0_F40_C9.interactive_data.excellentChoiceText',
  excellentChoiceDescription: 'scenes.S7.S7_D0_F40_C9.interactive_data.excellentChoiceDescription',
  goodApproximationText: 'scenes.S7.S7_D0_F40_C9.interactive_data.goodApproximationText',
  goodApproximationDescription: 'scenes.S7.S7_D0_F40_C9.interactive_data.goodApproximationDescription',
  seventeenToneText: 'scenes.S7.S7_D0_F40_C9.interactive_data.seventeenToneText',
  seventeenToneDescription: 'scenes.S7.S7_D0_F40_C9.interactive_data.seventeenToneDescription',
  nineteenToneText: 'scenes.S7.S7_D0_F40_C9.interactive_data.nineteenToneText',
  nineteenToneDescription: 'scenes.S7.S7_D0_F40_C9.interactive_data.nineteenToneDescription',
  veryAccurateText: 'scenes.S7.S7_D0_F40_C9.interactive_data.veryAccurateText',
  veryAccurateDescription: 'scenes.S7.S7_D0_F40_C9.interactive_data.veryAccurateDescription',
  yAxisLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.yAxisLabel',
  errorLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.errorLabel',
  pointAriaLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.pointAriaLabel',
  closestLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.closestLabel',
  perfectFifthLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.perfectFifthLabel',
  tooMessyLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.tooMessyLabel',
  complexSystemLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.complexSystemLabel',
  tooFineLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.tooFineLabel',
  testValuesText: 'scenes.S7.S7_D0_F40_C9.interactive_data.testValuesText',
  sliderAriaLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.sliderAriaLabel',
  chartAriaLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.chartAriaLabel',
  xAxisLabel: 'scenes.S7.S7_D0_F40_C9.interactive_data.xAxisLabel',
  approximatelyEquals: 'scenes.S7.S7_D0_F40_C9.interactive_data.approximatelyEquals',
  multipliedBy: 'scenes.S7.S7_D0_F40_C9.interactive_data.multipliedBy',
};

export default interaction;
