const interaction = {
  racePerformanceVisualization: 'scenes.S8.S8_D0_F42_C9.racePerformanceVisualization',
  currentTime: 'scenes.S8.S8_D0_F42_C9.currentTime',
  qualifyingTime: 'scenes.S8.S8_D0_F42_C9.qualifyingTime',
  speedAnalysisBySegment: 'scenes.S8.S8_D0_F42_C9.speedAnalysisBySegment',
  segment: 'scenes.S8.S8_D0_F42_C9.segment',
  distance: 'scenes.S8.S8_D0_F42_C9.distance',
  time: 'scenes.S8.S8_D0_F42_C9.time',
  speed: 'scenes.S8.S8_D0_F42_C9.speed',
  calculate: 'scenes.S8.S8_D0_F42_C9.calculate',
  calculateSpeedsAndAnalyzeRace: 'scenes.S8.S8_D0_F42_C9.calculateSpeedsAndAnalyzeRace',
  reset: 'scenes.S8.S8_D0_F42_C9.reset',
  distanceRateTimeCalculator: 'scenes.S8.S8_D0_F42_C9.distanceRateTimeCalculator',
  distanceRateTimeCalculatorAriaLabel: 'scenes.S8.S8_D0_F42_C9.distanceRateTimeCalculatorAriaLabel',
  distanceRateTimeCalculatorFeedback: 'scenes.S8.S8_D0_F42_C9.distanceRateTimeCalculatorFeedback',
  distanceRateTimeCalculatorFeedbackAriaLabel: 'scenes.S8.S8_D0_F42_C9.distanceRateTimeCalculatorFeedbackAriaLabel',
  distanceSpeedTimeFormulas: 'scenes.S8.S8_D0_F42_C9.distanceSpeedTimeFormulas',
  distanceSpeedTimeCalculator: 'scenes.S8.S8_D0_F42_C9.distanceSpeedTimeCalculator',
  meters: 'scenes.S8.S8_D0_F42_C9.meters',
  seconds: 'scenes.S8.S8_D0_F42_C9.seconds',
  metersPerSecond: 'scenes.S8.S8_D0_F42_C9.metersPerSecond',
  pleaseEnterExactlyTwoValuesToCalculateTheThird: 'scenes.S8.S8_D0_F42_C9.pleaseEnterExactlyTwoValuesToCalculateTheThird',
  ariaLabelDistanceFormular: 'scenes.S8.S8_D0_F42_C9.ariaLabelDistanceFormular',
  ariaLabelSpeedFormular: 'scenes.S8.S8_D0_F42_C9.ariaLabelSpeedFormular',
  ariaLabelTimeFormular: 'scenes.S8.S8_D0_F42_C9.ariaLabelTimeFormular',
  ariaLabelCurrentTime: 'scenes.S8.S8_D0_F42_C9.ariaLabelCurrentTime',
  ariaLabelQualifyingTime: 'scenes.S8.S8_D0_F42_C9.ariaLabelQualifyingTime',
  ariaLabelSegment: [
    'scenes.S8.S8_D0_F42_C9.ariaLabelSegment_1',
    'scenes.S8.S8_D0_F42_C9.ariaLabelSegment_2',
    'scenes.S8.S8_D0_F42_C9.ariaLabelSegment_3',
    'scenes.S8.S8_D0_F42_C9.ariaLabelSegment_4',
  ],
  solutionLabel: 'scenes.S8.S8_D0_F42_C9.solutionLabel',
  ariaDeleteIcon: 'scenes.S8.S8_D0_F42_C9.ariaDeleteIcon',
  lessThanOrEqualTo: 'scenes.S8.S8_D0_F42_C9.lessThanOrEqualTo',
  metersPerSeconds: 'scenes.S8.S8_D0_F42_C9.metersPerSeconds',
};

export default interaction;
