const circleCenterConstructionConfig = {
  totalSteps: 6,
  circleRadius: 120,
  canvasWidth: 600,
  canvasHeight: 450,
  actualCenter: { x: 300, y: 225 },
  ariaLabels: {
    construction_canvas: 'scenes.S7.S7_D0_F76_C9.ariaLabels.constructionCanvas',
    circle: 'scenes.S7.S7_D0_F76_C9.ariaLabels.circle',
    first_chord: 'scenes.S7.S7_D0_F76_C9.ariaLabels.firstChord',
    first_chord_point_1: 'scenes.S7.S7_D0_F76_C9.ariaLabels.firstChordPoint1',
    first_chord_point_2: 'scenes.S7.S7_D0_F76_C9.ariaLabels.firstChordPoint2',
    first_perpendicular_bisector: 'scenes.S7.S7_D0_F76_C9.ariaLabels.firstPerpendicularBisector',
    first_midpoint: 'scenes.S7.S7_D0_F76_C9.ariaLabels.firstMidpoint',
    second_chord: 'scenes.S7.S7_D0_F76_C9.ariaLabels.secondChord',
    second_chord_point_1: 'scenes.S7.S7_D0_F76_C9.ariaLabels.secondChordPoint1',
    second_chord_point_2: 'scenes.S7.S7_D0_F76_C9.ariaLabels.secondChordPoint2',
    second_perpendicular_bisector: 'scenes.S7.S7_D0_F76_C9.ariaLabels.secondPerpendicularBisector',
    second_midpoint: 'scenes.S7.S7_D0_F76_C9.ariaLabels.secondMidpoint',
    center_point: 'scenes.S7.S7_D0_F76_C9.ariaLabels.centerPoint',
    navigation_instruction: 'scenes.S7.S7_D0_F76_C9.ariaLabels.navigationInstruction',
    auto_create_first_chord: 'scenes.S7.S7_D0_F76_C9.ariaLabels.autoCreateFirstChord',
    auto_create_second_chord: 'scenes.S7.S7_D0_F76_C9.ariaLabels.autoCreateSecondChord',
    toggle_pb_construction: 'scenes.S7.S7_D0_F76_C9.ariaLabels.togglePBConstruction',
    hide_pb_construction: 'scenes.S7.S7_D0_F76_C9.ariaLabels.hidePBConstruction',
    show_pb_construction: 'scenes.S7.S7_D0_F76_C9.ariaLabels.showPBConstruction',
    construction_circles: 'scenes.S7.S7_D0_F76_C9.ariaLabels.constructionCircles',
    intersection_points: 'scenes.S7.S7_D0_F76_C9.ariaLabels.intersectionPoints',
    right_angle_indicator: 'scenes.S7.S7_D0_F76_C9.ariaLabels.rightAngleIndicator',
    accuracy_indicator: 'scenes.S7.S7_D0_F76_C9.ariaLabels.accuracyIndicator',
  },
};

export default circleCenterConstructionConfig;
