const interactive0Config = {
  goToSlide: "scenes.S4.S4_D0_FX_C9.go_to_slide",
  slimeProperties: [
    {
      emoji: '👧',
      heading: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.property_heading1',
      color: 'text-purple-800',
      description: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.property_description1',
      backgroundColor: 'from-purple-300 to-pink-300',
    },
    {
      emoji: '✨',
      heading: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.property_heading2',
      color: 'text-blue-800',
      description: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.property_description2',
      backgroundColor: 'from-blue-300 to-teal-300',
    },
  ],
  slimeVarieties: [
    { name: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.variety_name1', emoji: '✨', color: 'from-yellow-300 to-orange-300' },
    { name: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.variety_name2', emoji: '🌈', color: 'from-pink-300 to-purple-300' },
    { name: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.variety_name3', emoji: '💎', color: 'from-blue-300 to-cyan-300' },
    { name: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.variety_name4', emoji: '🎉', color: 'from-green-300 to-teal-300' },
    { name: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.variety_name5', emoji: '🔮', color: 'from-purple-300 to-indigo-300' },
    { name: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.variety_name6', emoji: '❄️', color: 'from-cyan-300 to-blue-300' },
    { name: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.variety_name7', emoji: '🍃', color: 'from-green-300 to-emerald-300' },
    { name: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.variety_name8', emoji: '🌸', color: 'from-pink-300 to-rose-300' },
  ],
  year1Data: {
    unitsSold: 4,
    revenue: 20,
    costs: 6,
    profit: 14,
  },
  year2Data: {
    unitsSold: 400,
    revenue: 2000,
    costs: 600,
    profit: 1400,
  },
  slides: [
    {
      id: 'title-slide',
      translations: {
        heading: 'scenes.S4.S4_D0_FX_C9.slides.title_slide.heading',
        presentedBy: 'scenes.S4.S4_D0_FX_C9.slides.title_slide.presentedBy',
        description: 'scenes.S4.S4_D0_FX_C9.slides.title_slide.description',
        label1: 'scenes.S4.S4_D0_FX_C9.slides.title_slide.label1',
        label2: 'scenes.S4.S4_D0_FX_C9.slides.title_slide.label2',
        label3: 'scenes.S4.S4_D0_FX_C9.slides.title_slide.label3',
      },
    },
    {
      id: 'product-slide',
      translations: {
        heading: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.heading',
        subheading: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.subheading',
        varietyTitle: 'scenes.S4.S4_D0_FX_C9.slides.product_slide.varietyTitle',
      },
    },
    {
      id: 'year1-slide',
      translations: {
        heading: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.heading',
        unitsSold: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.unitsSold',
        jarsTotal: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.jarsTotal',
        revenue: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.revenue',
        totalSales: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.totalSales',
        costs: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.costs',
        materials: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.materials',
        profit: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.profit',
        netIncome: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.netIncome',
        jarHeading: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.jarHeading',
        jarDescription: 'scenes.S4.S4_D0_FX_C9.slides.year1_slide.jarDescription',
      },
    },
    {
      id: 'year2-slide',
      translations: {
        heading: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.heading',
        year1: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.year1',
        year2: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.year2',
        unitsSold: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.unitsSold',
        revenue: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.revenue',
        profit: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.profit',
        graphTitle: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.graphTitle',
        xAxisLabel: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.xAxisLabel',
        yAxisLabel: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.yAxisLabel',
        graphDescription: 'scenes.S4.S4_D0_FX_C9.slides.year2_slide.graphDescription',
      },
    },
    {
      id: 'online-slide',
      translations: {
        heading: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.heading',
        strategyTitle1: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategyTitle1',
        strategyHeading1: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategyHeading1',
        strategySubheading1: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategySubheading1',
        strategyDescription1: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategyDescription1',
        strategyCost1: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategyCost1',
        strategyTitle2: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategyTitle2',
        strategyHeading2: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategyHeading2',
        strategySubheading2: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategySubheading2',
        strategyDescription2: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategyDescription2',
        strategyCost2: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.strategyCost2',
        videoPerformanceHeading: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.videoPerformanceHeading',
        videoPerformanceMatric1: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.videoPerformanceMatric1',
        videoPerformanceMatric2: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.videoPerformanceMatric2',
        videoPerformanceMatric3: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.videoPerformanceMatric3',
        opportunityHeading: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.opportunityHeading',
        opportunityDescription: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.opportunityDescription',
        opportunityAction: 'scenes.S4.S4_D0_FX_C9.slides.online_slide.opportunityAction',
      },
    },
  ],
};

export default interactive0Config;
