import { Interaction } from '../interactives/interface';

const interaction: Interaction = {
  type: 'fourier-visualizer',
  ariaLabel: 'scenes.S10.S10_D0_F83_C9.translations.ariaLabel',
  baseFreq: 440,
  waveTypes: [
    {
      label: 'scenes.S10.S10_D0_F83_C9.translations.sawtoothWave',
      value: 'sawtooth',
    },
    {
      label: 'scenes.S10.S10_D0_F83_C9.translations.squareWave',
      value: 'square',
    },
    {
      label: 'scenes.S10.S10_D0_F83_C9.translations.triangleWave',
      value: 'triangle',
    },
  ],
  translations: {
    play: 'scenes.S10.S10_D0_F83_C9.translations.play',
    pause: 'scenes.S10.S10_D0_F83_C9.translations.pause',
    waveTypeLabel: 'scenes.S10.S10_D0_F83_C9.translations.waveTypeLabel',
    compositeWaveLabel: 'scenes.S10.S10_D0_F83_C9.translations.compositeWaveLabel',
    useOddHarmonics: 'scenes.S10.S10_D0_F83_C9.translations.useOddHarmonics',
    useEvenHarmonics: 'scenes.S10.S10_D0_F83_C9.translations.useEvenHarmonics',
  },
  harmonicInputs: [
    {
      id: 'harmonic-1',
      label: 'scenes.S10.S10_D0_F83_C9.translations.harmonicLabel1',
      type: 'harmonic-input',
      enabled: true,
      freq: 440,
      freqMul: 1,
      color: '#E0002B',
      amplitude: {
        type: 'slider',
        id: 'amplitude-1',
        label: 'scenes.S10.S10_D0_F83_C9.translations.amplitude',
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.5,
      },
      phase: {
        type: 'slider',
        id: 'phase-1',
        label: 'scenes.S10.S10_D0_F83_C9.translations.phase',
        min: -Math.PI,
        max: Math.PI,
        step: 0.01,
        value: 0,
      },
    },
    {
      id: 'harmonic-2',
      label: 'scenes.S10.S10_D0_F83_C9.translations.harmonicLabel2',
      type: 'harmonic-input',
      enabled: true,
      freq: 880,
      freqMul: 2,
      color: '#00749D',
      amplitude: {
        type: 'slider',
        id: 'amplitude-2',
        label: 'scenes.S10.S10_D0_F83_C9.translations.amplitude',
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.5,
      },
      phase: {
        type: 'slider',
        id: 'phase-2',
        label: 'scenes.S10.S10_D0_F83_C9.translations.phase',
        min: -Math.PI,
        max: Math.PI,
        step: 0.01,
        value: 0,
      },
    },
    {
      id: 'harmonic-3',
      label: 'scenes.S10.S10_D0_F83_C9.translations.harmonicLabel3',
      type: 'harmonic-input',
      enabled: true,
      freq: 1320,
      freqMul: 3,
      color: '#8E24AA',
      amplitude: {
        type: 'slider',
        id: 'amplitude-3',
        label: 'scenes.S10.S10_D0_F83_C9.translations.amplitude',
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.5,
      },
      phase: {
        type: 'slider',
        id: 'phase-3',
        label: 'scenes.S10.S10_D0_F83_C9.translations.phase',
        min: -Math.PI,
        max: Math.PI,
        step: 0.01,
        value: 0,
      },
    },
    {
      id: 'harmonic-4',
      label: 'scenes.S10.S10_D0_F83_C9.translations.harmonicLabel4',
      type: 'harmonic-input',
      enabled: true,
      freq: 1760,
      freqMul: 4,
      color: '#008217',
      amplitude: {
        type: 'slider',
        id: 'amplitude-4',
        label: 'scenes.S10.S10_D0_F83_C9.translations.amplitude',
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.5,
      },
      phase: {
        type: 'slider',
        id: 'phase-4',
        label: 'scenes.S10.S10_D0_F83_C9.translations.phase',
        min: -Math.PI,
        max: Math.PI,
        step: 0.01,
        value: 0,
      },
    },
    {
      id: 'harmonic-5',
      label: 'scenes.S10.S10_D0_F83_C9.translations.harmonicLabel5',
      type: 'harmonic-input',
      enabled: true,
      freq: 2200,
      freqMul: 5,
      color: '#DB0072',
      amplitude: {
        type: 'slider',
        id: 'amplitude-5',
        label: 'scenes.S10.S10_D0_F83_C9.translations.amplitude',
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.5,
      },
      phase: {
        type: 'slider',
        id: 'phase-5',
        label: 'scenes.S10.S10_D0_F83_C9.translations.phase',
        min: -Math.PI,
        max: Math.PI,
        step: 0.01,
        value: 0,
      },
    },
    {
      id: 'harmonic-6',
      label: 'scenes.S10.S10_D0_F83_C9.translations.harmonicLabel6',
      type: 'harmonic-input',
      enabled: true,
      freq: 2640,
      freqMul: 6,
      color: '#D14700',
      amplitude: {
        type: 'slider',
        id: 'amplitude-6',
        label: 'scenes.S10.S10_D0_F83_C9.translations.amplitude',
        min: 0,
        max: 1,
        step: 0.01,
        value: 0.5,
      },
      phase: {
        type: 'slider',
        id: 'phase-6',
        label: 'scenes.S10.S10_D0_F83_C9.translations.phase',
        min: -Math.PI,
        max: Math.PI,
        step: 0.01,
        value: 0,
      },
    },
  ],
  getInitialHarmonics: (type: string) => {
    switch (type) {
      case 'square':
        return [
          { id: 'harmonic-1', freqMul: 1, amp: 1.0, phase: 0 },
          { id: 'harmonic-2', freqMul: 2, amp: 1.0, phase: 0 },
          { id: 'harmonic-3', freqMul: 3, amp: 0.3, phase: 0 },
          { id: 'harmonic-4', freqMul: 4, amp: 0.3, phase: 0 },
          { id: 'harmonic-5', freqMul: 5, amp: 0.2, phase: 0 },
          { id: 'harmonic-6', freqMul: 6, amp: 0.2, phase: 0 },
        ];
      case 'sawtooth':
        return [
          { id: 'harmonic-1', freqMul: 1, amp: 1.0, phase: 0 },
          { id: 'harmonic-2', freqMul: 2, amp: 0.5, phase: Math.PI },
          { id: 'harmonic-3', freqMul: 3, amp: 0.33, phase: 0 },
          { id: 'harmonic-4', freqMul: 4, amp: 0.25, phase: Math.PI },
          { id: 'harmonic-5', freqMul: 5, amp: 0.2, phase: 0 },
          { id: 'harmonic-6', freqMul: 6, amp: 0.17, phase: Math.PI },
        ];
      case 'triangle':
        return [
          { id: 'harmonic-1', freqMul: 1, amp: 1.0, phase: 0 },
          { id: 'harmonic-2', freqMul: 2, amp: 0.07, phase: 0 },
          { id: 'harmonic-3', freqMul: 3, amp: 0.11, phase: Math.PI },
          { id: 'harmonic-4', freqMul: 4, amp: 0.04, phase: 0 },
          { id: 'harmonic-5', freqMul: 5, amp: 0.04, phase: 0 },
          { id: 'harmonic-6', freqMul: 6, amp: 0.02, phase: 0 },
        ];
      default:
        return [];
    }
  },
};
export default interaction;
