import { Interaction } from '../interactives/interface';

const interaction: Interaction = {
  type: 'attack-phase-function',
  totalSteps: 4,
  inputs: [
    {
      id: 'verticalShift',
      type: 'slider',
      label: 'scenes.S6.S6_D0_F27_C9.translations.verticalShiftLabel',
      min: 0,
      max: 1,
      value: 0.2,
      step: 0.1,
    },
    {
      id: 'verticalScale',
      type: 'slider',
      label: 'scenes.S6.S6_D0_F27_C9.translations.verticalScaleLabel',
      min: 0.5,
      max: 2.5,
      value: 1.5,
      step: 0.1,
    },
    {
      id: 'horizontalShift',
      type: 'slider',
      label: 'scenes.S6.S6_D0_F27_C9.translations.horizontalShiftLabel',
      min: 0,
      max: 1,
      value: 0.1,
      step: 0.1,
    },
    {
      id: 'horizontalScale',
      type: 'slider',
      label: 'scenes.S6.S6_D0_F27_C9.translations.horizontalScaleLabel',
      min: 0,
      max: 2,
      value: 0.8,
      step: 0.1,
    },
  ],
  translations: {
    originalFunctionLabel: 'scenes.S6.S6_D0_F27_C9.translations.originalFunctionLabel',
    originalFunctionAriaLabel: 'scenes.S6.S6_D0_F27_C9.translations.originalFunctionAriaLabel',
    transformedFunctionLabel: 'scenes.S6.S6_D0_F27_C9.translations.transformedFunctionLabel',
    transformedFunctionAriaLabel: 'scenes.S6.S6_D0_F27_C9.translations.transformedFunctionAriaLabel',
    functionTransformationsLabel: 'scenes.S6.S6_D0_F27_C9.translations.functionTransformationsLabel',
    functionTransDescription: 'scenes.S6.S6_D0_F27_C9.translations.functionTransDescription',
    testLabel: 'scenes.S6.S6_D0_F27_C9.translations.testLabel',
    testDescription: 'scenes.S6.S6_D0_F27_C9.translations.testDescription',
    playLabel: 'scenes.S6.S6_D0_F27_C9.translations.playLabel',
    transformed: 'scenes.S6.S6_D0_F27_C9.translations.transformed',
    xAxisLabel: 'scenes.S6.S6_D0_F27_C9.translations.xAxisLabel',
    yAxisLabel: 'scenes.S6.S6_D0_F27_C9.translations.yAxisLabel',
    volumeLabel: 'scenes.S6.S6_D0_F27_C9.translations.volumeLabel',
    target: 'scenes.S6.S6_D0_F27_C9.translations.target',
    functionDescription: 'scenes.S6.S6_D0_F27_C9.translations.functionDescription',
    attack: 'scenes.S6.S6_D0_F27_C9.translations.attack',
    targetFunctionLabel: 'scenes.S6.S6_D0_F27_C9.translations.targetFunctionLabel',
    targetFunctionAriaLabel: 'scenes.S6.S6_D0_F27_C9.translations.targetFunctionAriaLabel',
  },
};
export default interaction;
