import { Interaction } from '../interactives/interface';

const interaction: Interaction = {
  type: 'remix-beats-with-adsr',
  totalSteps: 2,
  adsrInputs: {
    kick: {
      attack: {
        id: 'kick-attack',
        type: 'slider',
        label: 'scenes.S9.S9_D0_F76_C9.translations.attack',
        min: 0.01,
        max: 0.1,
        value: 0.05,
        step: 0.01,
        unit: 's',
      },
      decay: {
        id: 'kick-decay',
        type: 'slider',
        label: 'scenes.S9.S9_D0_F76_C9.translations.decay',
        min: 0.01,
        max: 0.5,
        value: 0.25,
        step: 0.01,
        unit: 's',
      },
      sustain: {
        id: 'kick-sustain',
        type: 'slider',
        label: 'scenes.S9.S9_D0_F76_C9.translations.sustain',
        min: 0,
        max: 1,
        value: 0.3,
        step: 0.01,
        unit: '%',
      },
      release: {
        id: 'kick-release',
        type: 'slider',
        label: 'scenes.S9.S9_D0_F76_C9.translations.release',
        min: 0.01,
        max: 1,
        value: 0.3,
        step: 0.01,
        unit: 's',
      },
    },
    cymbal: {
      attack: {
        id: 'cymbal-attack',
        type: 'slider',
        label: 'scenes.S9.S9_D0_F76_C9.translations.attack',
        min: 0.01,
        max: 0.1,
        value: 0.01,
        step: 0.01,
        unit: 's',
      },
      decay: {
        id: 'cymbal-decay',
        type: 'slider',
        label: 'scenes.S9.S9_D0_F76_C9.translations.decay',
        min: 0.05,
        max: 1,
        value: 0.5,
        step: 0.01,
        unit: 's',
      },
      sustain: {
        id: 'cymbal-sustain',
        type: 'slider',
        label: 'scenes.S9.S9_D0_F76_C9.translations.sustain',
        min: 0,
        max: 0.2,
        value: 0.03,
        step: 0.01,
        unit: '%',
      },
      release: {
        id: 'cymbal-release',
        type: 'slider',
        label: 'scenes.S9.S9_D0_F76_C9.translations.release',
        min: 0.1,
        max: 2,
        value: 0.6,
        step: 0.1,
        unit: 's',
      },
    },
  },
  translations: {
    secondsLabel: 'scenes.S9.S9_D0_F76_C9.translations.secondsLabel',
    playLabel: 'scenes.S9.S9_D0_F76_C9.translations.playLabel',
    stopLabel: 'scenes.S9.S9_D0_F76_C9.translations.stopLabel',
    editingLabel: 'scenes.S9.S9_D0_F76_C9.translations.editingLabel',
    selectedLabel: 'scenes.S9.S9_D0_F76_C9.translations.selectedLabel',
    kickInstrument: 'scenes.S9.S9_D0_F76_C9.translations.kickInstrument',
    cymbalInstrument: 'scenes.S9.S9_D0_F76_C9.translations.cymbalInstrument',
  },
};

export default interaction;
